/**
 * Regenerate `packages/core/src/bullmq/vendored.generated.ts` from the
 * installed `bullmq` devDependency (its pre-bundled Lua, includes inlined).
 *
 *   bun apps/agent/src/handlers/queue-op.vendor.ts
 *
 * Only the MUTATION scripts the queue studio runs are vendored — the exact
 * scripts BullMQ's own Queue/Job methods call, so a studio retry/promote/
 * remove/clean/pause leaves the queue in the state a `Queue` client would
 * (markers, events stream, priority counter, paused meta). swarmy's read-only
 * scripts live beside it in `lua.ts`. The drift test
 * (`handlers/queue-op.integration.test.ts`) fails when the installed bullmq
 * no longer matches the vendored copy — bump both together.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

export const SCRIPTS = [
  'reprocessJob-8',
  'moveJobsToWait-8',
  'promote-9',
  'removeJob-2',
  'cleanJobsInSet-3',
  'pause-7',
  'drain-5',
] as const;

const agentRoot = path.resolve(import.meta.dir, '..', '..');
const bullmqRoot = path.join(agentRoot, 'node_modules', 'bullmq');
const out = path.resolve(agentRoot, '..', '..', 'packages', 'core', 'src', 'bullmq', 'vendored.generated.ts');

/** The script's Lua exactly as bullmq ships it (the module's own `content`). */
export async function readInstalledScript(file: string): Promise<string> {
  const mod = (await import(path.join(bullmqRoot, 'dist', 'esm', 'scripts', `${file}.js`))) as Record<
    string,
    { content?: string }
  >;
  const content = Object.values(mod).find((v) => typeof v?.content === 'string')?.content;
  if (!content) throw new Error(`no Lua content exported by bullmq ${file}.js`);
  return content;
}

export function installedBullmqVersion(): string {
  return (JSON.parse(readFileSync(path.join(bullmqRoot, 'package.json'), 'utf8')) as { version: string }).version;
}

export function constName(file: string): string {
  return `${file.split('-')[0]!.toUpperCase()}_LUA`;
}

if (import.meta.main) {
  const version = installedBullmqVersion();
  const parts: string[] = [];
  for (const f of SCRIPTS) {
    const keys = Number(f.split('-')[1]);
    parts.push(
      [
        `/** BullMQ \`${f}.lua\` (${keys} KEYS). */`,
        `export const ${constName(f)} = { name: '${f.split('-')[0]}', keys: ${keys}, content: ${JSON.stringify(await readInstalledScript(f))} } as const;`,
      ].join('\n'),
    );
  }
  const body = parts.join('\n\n');
  writeFileSync(
    out,
    [
      '/* eslint-disable */',
      '// GENERATED by apps/agent/src/handlers/queue-op.vendor.ts — do not edit.',
      `// Source: bullmq@${version} dist/esm/scripts (Lua with includes inlined).`,
      '//',
      '// BullMQ is MIT licensed: Copyright (c) 2018 BullForce Labs AB and contributors.',
      '// Permission is hereby granted, free of charge, to any person obtaining a copy of',
      '// this software, to deal in the Software without restriction (full text:',
      '// https://github.com/taskforcesh/bullmq/blob/master/LICENSE). THE SOFTWARE IS',
      '// PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.',
      '',
      `export const VENDORED_BULLMQ_VERSION = '${version}';`,
      '',
      body,
      '',
    ].join('\n'),
  );
  console.log(`wrote ${path.relative(process.cwd(), out)} from bullmq@${version}`);
}
