/**
 * Boot-time schema bring-up.
 *
 * The controller boots on whatever is in its data dir, often nothing, so it
 * migrates itself: `ensureSchema()` applies the Prisma migration SQL (in name
 * order) through the active adapter, recording each one in `_swarmy_migrations`
 * so restarts are no-ops. Each migration runs in its own transaction, so a
 * failing one leaves the file as it was.
 *
 * control.db migrations live in prisma/migrations, telemetry.db's in
 * prisma/telemetry/migrations. Both are generated by `prisma migrate diff`
 * (see the `db:migration` scripts in package.json), never written by hand.
 */
import { readdir, readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { SqlDriverAdapter, SqlDriverAdapterFactory } from '@prisma/driver-adapter-utils';

const MIGRATIONS_TABLE = '_swarmy_migrations';

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
/** control.db migrations. */
export const CONTROL_MIGRATIONS_DIR = join(pkgRoot, 'prisma', 'migrations');
/** telemetry.db migrations. */
export const TELEMETRY_MIGRATIONS_DIR = join(pkgRoot, 'prisma', 'telemetry', 'migrations');

async function listMigrationFiles(dir: string): Promise<{ name: string; sql: string }[]> {
  let entries: string[];
  try {
    entries = (await readdir(dir, { withFileTypes: true }))
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
      .sort();
  } catch {
    return [];
  }
  const out: { name: string; sql: string }[] = [];
  for (const name of entries) {
    try {
      const sql = await readFile(join(dir, name, 'migration.sql'), 'utf8');
      out.push({ name, sql });
    } catch {
      // skip dirs without a migration.sql
    }
  }
  return out;
}

/**
 * Apply all pending migrations against `adapterFactory`. Returns the names
 * freshly applied (empty if already up to date).
 *
 * @param dir the migrations directory (default: control.db's).
 */
export async function ensureSchema(
  adapterFactory: SqlDriverAdapterFactory,
  dir: string = CONTROL_MIGRATIONS_DIR,
): Promise<string[]> {
  const adapter: SqlDriverAdapter = await adapterFactory.connect();
  try {
    await adapter.executeScript(
      `CREATE TABLE IF NOT EXISTS "${MIGRATIONS_TABLE}" (name TEXT PRIMARY KEY, applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);`,
    );
    const appliedRes = await adapter.queryRaw({
      sql: `SELECT name FROM "${MIGRATIONS_TABLE}"`,
      args: [],
      argTypes: [],
    });
    const applied = new Set(appliedRes.rows.map((r) => String(r[0])));

    const freshlyApplied: string[] = [];
    for (const { name, sql } of await listMigrationFiles(dir)) {
      if (applied.has(name)) continue;
      // startTransaction() opens BEGIN on the one handle, so the script below
      // runs inside it; COMMIT/ROLLBACK are ours to send (usePhantomQuery: false).
      const tx = await adapter.startTransaction();
      try {
        await adapter.executeScript(sql);
        await tx.executeRaw({
          sql: `INSERT INTO "${MIGRATIONS_TABLE}" (name) VALUES (?)`,
          args: [name],
          argTypes: [{ scalarType: 'string', arity: 'scalar' }],
        });
        await tx.executeRaw({ sql: 'COMMIT', args: [], argTypes: [] });
        await tx.commit();
      } catch (e) {
        await tx.executeRaw({ sql: 'ROLLBACK', args: [], argTypes: [] }).catch(() => undefined);
        await tx.rollback();
        throw new Error(`migration ${name} failed: ${e instanceof Error ? e.message : String(e)}`);
      }
      freshlyApplied.push(name);
    }
    return freshlyApplied;
  } finally {
    await adapter.dispose();
  }
}
