/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppLoginRouteImport } from './routes/app-login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as AuthedTelemetryRouteImport } from './routes/_authed/telemetry'
import { Route as AuthedStatusPagesRouteImport } from './routes/_authed/status-pages'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedOverviewRouteImport } from './routes/_authed/overview'
import { Route as AuthedNetworkingRouteImport } from './routes/_authed/networking'
import { Route as AuthedNetworkRouteImport } from './routes/_authed/network'
import { Route as AuthedIngressRouteImport } from './routes/_authed/ingress'
import { Route as AuthedIncidentsRouteImport } from './routes/_authed/incidents'
import { Route as AuthedGovernanceRouteImport } from './routes/_authed/governance'
import { Route as AuthedEmailRouteImport } from './routes/_authed/email'
import { Route as AuthedDeviceRouteImport } from './routes/_authed/device'
import { Route as AuthedDeployRouteImport } from './routes/_authed/deploy'
import { Route as AuthedDataRouteImport } from './routes/_authed/data'
import { Route as AuthedCostRouteImport } from './routes/_authed/cost'
import { Route as AuthedCiRouteImport } from './routes/_authed/ci'
import { Route as AuthedBlueprintsRouteImport } from './routes/_authed/blueprints'
import { Route as AuthedBackupsRouteImport } from './routes/_authed/backups'
import { Route as AuthedAuditRouteImport } from './routes/_authed/audit'
import { Route as AuthedAlertsRouteImport } from './routes/_authed/alerts'
import { Route as AuthedAiRouteImport } from './routes/_authed/ai'
import { Route as AuthedActivityRouteImport } from './routes/_authed/activity'
import { Route as AuthedSplatRouteImport } from './routes/_authed/$'
import { Route as AuthedNodesIndexRouteImport } from './routes/_authed/nodes/index'
import { Route as AuthedStacksNewRouteImport } from './routes/_authed/stacks/new'
import { Route as AuthedStacksNameRouteImport } from './routes/_authed/stacks/$name'
import { Route as AuthedSettingsPlatformRouteImport } from './routes/_authed/settings_.platform'
import { Route as AuthedSettingsApiKeysRouteImport } from './routes/_authed/settings_.api-keys'
import { Route as AuthedSettingsAccessRouteImport } from './routes/_authed/settings_.access'
import { Route as AuthedServicesNewRouteImport } from './routes/_authed/services/new'
import { Route as AuthedServicesServiceIdRouteImport } from './routes/_authed/services/$serviceId'
import { Route as AuthedObservabilityTraceIdRouteImport } from './routes/_authed/observability.$traceId'
import { Route as AuthedNodesNewRouteImport } from './routes/_authed/nodes/new'
import { Route as AuthedNodesNodeIdRouteImport } from './routes/_authed/nodes/$nodeId'
import { Route as AuthedIncidentsIncidentIdRouteImport } from './routes/_authed/incidents_.$incidentId'
import { Route as AuthedDeployTemplateRouteImport } from './routes/_authed/deploy_.$template'
import { Route as AuthedDataBucketsRouteImport } from './routes/_authed/data_.buckets'
import { Route as AuthedCiBuildIdRouteImport } from './routes/_authed/ci_.$buildId'
import { Route as AuthedStacksNameIndexRouteImport } from './routes/_authed/stacks/$name.index'
import { Route as AuthedTerminalSessionsIdRouteImport } from './routes/_authed/terminal.sessions.$id'
import { Route as AuthedStacksNameStudioRouteImport } from './routes/_authed/stacks/$name.studio'
import { Route as AuthedStacksNameSourceRouteImport } from './routes/_authed/stacks/$name.source'
import { Route as AuthedStacksNameSettingsRouteImport } from './routes/_authed/stacks/$name.settings'
import { Route as AuthedStacksNameRumSettingsRouteImport } from './routes/_authed/stacks/$name.rum-settings'
import { Route as AuthedStacksNameReleasesRouteImport } from './routes/_authed/stacks/$name.releases'
import { Route as AuthedStacksNameObservabilityRouteImport } from './routes/_authed/stacks/$name.observability'
import { Route as AuthedStacksNameNetworkRouteImport } from './routes/_authed/stacks/$name.network'
import { Route as AuthedStacksNameMessagingRouteImport } from './routes/_authed/stacks/$name.messaging'
import { Route as AuthedStacksNameDataRouteImport } from './routes/_authed/stacks/$name.data'
import { Route as AuthedStacksNameBackupsRouteImport } from './routes/_authed/stacks/$name.backups'
import { Route as AuthedStacksNameAnalyticsRouteImport } from './routes/_authed/stacks/$name.analytics'
import { Route as AuthedStacksNameAccessRouteImport } from './routes/_authed/stacks/$name.access'
import { Route as AuthedServicesServiceIdTerminalRouteImport } from './routes/_authed/services/$serviceId_.terminal'
import { Route as AuthedNodesNodeIdTerminalRouteImport } from './routes/_authed/nodes/$nodeId_.terminal'
import { Route as AuthedNetworkDomainsNewRouteImport } from './routes/_authed/network_.domains.new'
import { Route as AuthedNetworkDomainsHostRouteImport } from './routes/_authed/network_.domains.$host'
import { Route as AuthedStacksNameReplaysIndexRouteImport } from './routes/_authed/stacks/$name.replays.index'
import { Route as AuthedStacksNameQueuesIndexRouteImport } from './routes/_authed/stacks/$name.queues.index'
import { Route as AuthedStacksNameErrorsIndexRouteImport } from './routes/_authed/stacks/$name.errors.index'
import { Route as AuthedStacksNameConfigIndexRouteImport } from './routes/_authed/stacks/$name.config.index'
import { Route as AuthedStacksNameReplaysSessionIdRouteImport } from './routes/_authed/stacks/$name.replays.$sessionId'
import { Route as AuthedStacksNameQueuesClusterRouteImport } from './routes/_authed/stacks/$name.queues.$cluster'
import { Route as AuthedStacksNameErrorsFingerprintRouteImport } from './routes/_authed/stacks/$name.errors.$fingerprint'
import { Route as AuthedStacksNameConfigScalingRouteImport } from './routes/_authed/stacks/$name.config.scaling'
import { Route as AuthedStacksNameConfigRolloutRouteImport } from './routes/_authed/stacks/$name.config.rollout'
import { Route as AuthedStacksNameConfigPlacementRouteImport } from './routes/_authed/stacks/$name.config.placement'
import { Route as AuthedStacksNameConfigJobsRouteImport } from './routes/_authed/stacks/$name.config.jobs'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/app-login',
  path: '/app-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTelemetryRoute = AuthedTelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStatusPagesRoute = AuthedStatusPagesRouteImport.update({
  id: '/status-pages',
  path: '/status-pages',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOverviewRoute = AuthedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNetworkingRoute = AuthedNetworkingRouteImport.update({
  id: '/networking',
  path: '/networking',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNetworkRoute = AuthedNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIngressRoute = AuthedIngressRouteImport.update({
  id: '/ingress',
  path: '/ingress',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIncidentsRoute = AuthedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGovernanceRoute = AuthedGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEmailRoute = AuthedEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDeviceRoute = AuthedDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDeployRoute = AuthedDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDataRoute = AuthedDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCostRoute = AuthedCostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCiRoute = AuthedCiRouteImport.update({
  id: '/ci',
  path: '/ci',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBlueprintsRoute = AuthedBlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBackupsRoute = AuthedBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditRoute = AuthedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAlertsRoute = AuthedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAiRoute = AuthedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedActivityRoute = AuthedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSplatRoute = AuthedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNodesIndexRoute = AuthedNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStacksNewRoute = AuthedStacksNewRouteImport.update({
  id: '/stacks/new',
  path: '/stacks/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStacksNameRoute = AuthedStacksNameRouteImport.update({
  id: '/stacks/$name',
  path: '/stacks/$name',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsPlatformRoute = AuthedSettingsPlatformRouteImport.update({
  id: '/settings_/platform',
  path: '/settings/platform',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsApiKeysRoute = AuthedSettingsApiKeysRouteImport.update({
  id: '/settings_/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsAccessRoute = AuthedSettingsAccessRouteImport.update({
  id: '/settings_/access',
  path: '/settings/access',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServicesNewRoute = AuthedServicesNewRouteImport.update({
  id: '/services/new',
  path: '/services/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServicesServiceIdRoute = AuthedServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedObservabilityTraceIdRoute =
  AuthedObservabilityTraceIdRouteImport.update({
    id: '/observability/$traceId',
    path: '/observability/$traceId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedNodesNewRoute = AuthedNodesNewRouteImport.update({
  id: '/nodes/new',
  path: '/nodes/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNodesNodeIdRoute = AuthedNodesNodeIdRouteImport.update({
  id: '/nodes/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIncidentsIncidentIdRoute =
  AuthedIncidentsIncidentIdRouteImport.update({
    id: '/incidents_/$incidentId',
    path: '/incidents/$incidentId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDeployTemplateRoute = AuthedDeployTemplateRouteImport.update({
  id: '/deploy_/$template',
  path: '/deploy/$template',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDataBucketsRoute = AuthedDataBucketsRouteImport.update({
  id: '/data_/buckets',
  path: '/data/buckets',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCiBuildIdRoute = AuthedCiBuildIdRouteImport.update({
  id: '/ci_/$buildId',
  path: '/ci/$buildId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStacksNameIndexRoute = AuthedStacksNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedStacksNameRoute,
} as any)
const AuthedTerminalSessionsIdRoute =
  AuthedTerminalSessionsIdRouteImport.update({
    id: '/terminal/sessions/$id',
    path: '/terminal/sessions/$id',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedStacksNameStudioRoute = AuthedStacksNameStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthedStacksNameRoute,
} as any)
const AuthedStacksNameSourceRoute = AuthedStacksNameSourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => AuthedStacksNameRoute,
} as any)
const AuthedStacksNameSettingsRoute =
  AuthedStacksNameSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameRumSettingsRoute =
  AuthedStacksNameRumSettingsRouteImport.update({
    id: '/rum-settings',
    path: '/rum-settings',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameReleasesRoute =
  AuthedStacksNameReleasesRouteImport.update({
    id: '/releases',
    path: '/releases',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameObservabilityRoute =
  AuthedStacksNameObservabilityRouteImport.update({
    id: '/observability',
    path: '/observability',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameNetworkRoute = AuthedStacksNameNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthedStacksNameRoute,
} as any)
const AuthedStacksNameMessagingRoute =
  AuthedStacksNameMessagingRouteImport.update({
    id: '/messaging',
    path: '/messaging',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameDataRoute = AuthedStacksNameDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AuthedStacksNameRoute,
} as any)
const AuthedStacksNameBackupsRoute = AuthedStacksNameBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthedStacksNameRoute,
} as any)
const AuthedStacksNameAnalyticsRoute =
  AuthedStacksNameAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameAccessRoute = AuthedStacksNameAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AuthedStacksNameRoute,
} as any)
const AuthedServicesServiceIdTerminalRoute =
  AuthedServicesServiceIdTerminalRouteImport.update({
    id: '/services/$serviceId_/terminal',
    path: '/services/$serviceId/terminal',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedNodesNodeIdTerminalRoute =
  AuthedNodesNodeIdTerminalRouteImport.update({
    id: '/nodes/$nodeId_/terminal',
    path: '/nodes/$nodeId/terminal',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedNetworkDomainsNewRoute = AuthedNetworkDomainsNewRouteImport.update({
  id: '/network_/domains/new',
  path: '/network/domains/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNetworkDomainsHostRoute =
  AuthedNetworkDomainsHostRouteImport.update({
    id: '/network_/domains/$host',
    path: '/network/domains/$host',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedStacksNameReplaysIndexRoute =
  AuthedStacksNameReplaysIndexRouteImport.update({
    id: '/replays/',
    path: '/replays/',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameQueuesIndexRoute =
  AuthedStacksNameQueuesIndexRouteImport.update({
    id: '/queues/',
    path: '/queues/',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameErrorsIndexRoute =
  AuthedStacksNameErrorsIndexRouteImport.update({
    id: '/errors/',
    path: '/errors/',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameConfigIndexRoute =
  AuthedStacksNameConfigIndexRouteImport.update({
    id: '/config/',
    path: '/config/',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameReplaysSessionIdRoute =
  AuthedStacksNameReplaysSessionIdRouteImport.update({
    id: '/replays/$sessionId',
    path: '/replays/$sessionId',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameQueuesClusterRoute =
  AuthedStacksNameQueuesClusterRouteImport.update({
    id: '/queues/$cluster',
    path: '/queues/$cluster',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameErrorsFingerprintRoute =
  AuthedStacksNameErrorsFingerprintRouteImport.update({
    id: '/errors/$fingerprint',
    path: '/errors/$fingerprint',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameConfigScalingRoute =
  AuthedStacksNameConfigScalingRouteImport.update({
    id: '/config/scaling',
    path: '/config/scaling',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameConfigRolloutRoute =
  AuthedStacksNameConfigRolloutRouteImport.update({
    id: '/config/rollout',
    path: '/config/rollout',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameConfigPlacementRoute =
  AuthedStacksNameConfigPlacementRouteImport.update({
    id: '/config/placement',
    path: '/config/placement',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameConfigJobsRoute =
  AuthedStacksNameConfigJobsRouteImport.update({
    id: '/config/jobs',
    path: '/config/jobs',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/app-login': typeof AppLoginRoute
  '/login': typeof LoginRoute
  '/$': typeof AuthedSplatRoute
  '/activity': typeof AuthedActivityRoute
  '/ai': typeof AuthedAiRoute
  '/alerts': typeof AuthedAlertsRoute
  '/audit': typeof AuthedAuditRoute
  '/backups': typeof AuthedBackupsRoute
  '/blueprints': typeof AuthedBlueprintsRoute
  '/ci': typeof AuthedCiRoute
  '/cost': typeof AuthedCostRoute
  '/data': typeof AuthedDataRoute
  '/deploy': typeof AuthedDeployRoute
  '/device': typeof AuthedDeviceRoute
  '/email': typeof AuthedEmailRoute
  '/governance': typeof AuthedGovernanceRoute
  '/incidents': typeof AuthedIncidentsRoute
  '/ingress': typeof AuthedIngressRoute
  '/network': typeof AuthedNetworkRoute
  '/networking': typeof AuthedNetworkingRoute
  '/overview': typeof AuthedOverviewRoute
  '/settings': typeof AuthedSettingsRoute
  '/status-pages': typeof AuthedStatusPagesRoute
  '/telemetry': typeof AuthedTelemetryRoute
  '/join/$token': typeof JoinTokenRoute
  '/s/$slug': typeof SSlugRoute
  '/ci/$buildId': typeof AuthedCiBuildIdRoute
  '/data/buckets': typeof AuthedDataBucketsRoute
  '/deploy/$template': typeof AuthedDeployTemplateRoute
  '/incidents/$incidentId': typeof AuthedIncidentsIncidentIdRoute
  '/nodes/$nodeId': typeof AuthedNodesNodeIdRoute
  '/nodes/new': typeof AuthedNodesNewRoute
  '/observability/$traceId': typeof AuthedObservabilityTraceIdRoute
  '/services/$serviceId': typeof AuthedServicesServiceIdRoute
  '/services/new': typeof AuthedServicesNewRoute
  '/settings/access': typeof AuthedSettingsAccessRoute
  '/settings/api-keys': typeof AuthedSettingsApiKeysRoute
  '/settings/platform': typeof AuthedSettingsPlatformRoute
  '/stacks/$name': typeof AuthedStacksNameRouteWithChildren
  '/stacks/new': typeof AuthedStacksNewRoute
  '/nodes/': typeof AuthedNodesIndexRoute
  '/network/domains/$host': typeof AuthedNetworkDomainsHostRoute
  '/network/domains/new': typeof AuthedNetworkDomainsNewRoute
  '/nodes/$nodeId/terminal': typeof AuthedNodesNodeIdTerminalRoute
  '/services/$serviceId/terminal': typeof AuthedServicesServiceIdTerminalRoute
  '/stacks/$name/access': typeof AuthedStacksNameAccessRoute
  '/stacks/$name/analytics': typeof AuthedStacksNameAnalyticsRoute
  '/stacks/$name/backups': typeof AuthedStacksNameBackupsRoute
  '/stacks/$name/data': typeof AuthedStacksNameDataRoute
  '/stacks/$name/messaging': typeof AuthedStacksNameMessagingRoute
  '/stacks/$name/network': typeof AuthedStacksNameNetworkRoute
  '/stacks/$name/observability': typeof AuthedStacksNameObservabilityRoute
  '/stacks/$name/releases': typeof AuthedStacksNameReleasesRoute
  '/stacks/$name/rum-settings': typeof AuthedStacksNameRumSettingsRoute
  '/stacks/$name/settings': typeof AuthedStacksNameSettingsRoute
  '/stacks/$name/source': typeof AuthedStacksNameSourceRoute
  '/stacks/$name/studio': typeof AuthedStacksNameStudioRoute
  '/terminal/sessions/$id': typeof AuthedTerminalSessionsIdRoute
  '/stacks/$name/': typeof AuthedStacksNameIndexRoute
  '/stacks/$name/config/jobs': typeof AuthedStacksNameConfigJobsRoute
  '/stacks/$name/config/placement': typeof AuthedStacksNameConfigPlacementRoute
  '/stacks/$name/config/rollout': typeof AuthedStacksNameConfigRolloutRoute
  '/stacks/$name/config/scaling': typeof AuthedStacksNameConfigScalingRoute
  '/stacks/$name/errors/$fingerprint': typeof AuthedStacksNameErrorsFingerprintRoute
  '/stacks/$name/queues/$cluster': typeof AuthedStacksNameQueuesClusterRoute
  '/stacks/$name/replays/$sessionId': typeof AuthedStacksNameReplaysSessionIdRoute
  '/stacks/$name/config/': typeof AuthedStacksNameConfigIndexRoute
  '/stacks/$name/errors/': typeof AuthedStacksNameErrorsIndexRoute
  '/stacks/$name/queues/': typeof AuthedStacksNameQueuesIndexRoute
  '/stacks/$name/replays/': typeof AuthedStacksNameReplaysIndexRoute
}
export interface FileRoutesByTo {
  '/app-login': typeof AppLoginRoute
  '/login': typeof LoginRoute
  '/$': typeof AuthedSplatRoute
  '/activity': typeof AuthedActivityRoute
  '/ai': typeof AuthedAiRoute
  '/alerts': typeof AuthedAlertsRoute
  '/audit': typeof AuthedAuditRoute
  '/backups': typeof AuthedBackupsRoute
  '/blueprints': typeof AuthedBlueprintsRoute
  '/ci': typeof AuthedCiRoute
  '/cost': typeof AuthedCostRoute
  '/data': typeof AuthedDataRoute
  '/deploy': typeof AuthedDeployRoute
  '/device': typeof AuthedDeviceRoute
  '/email': typeof AuthedEmailRoute
  '/governance': typeof AuthedGovernanceRoute
  '/incidents': typeof AuthedIncidentsRoute
  '/ingress': typeof AuthedIngressRoute
  '/network': typeof AuthedNetworkRoute
  '/networking': typeof AuthedNetworkingRoute
  '/overview': typeof AuthedOverviewRoute
  '/settings': typeof AuthedSettingsRoute
  '/status-pages': typeof AuthedStatusPagesRoute
  '/telemetry': typeof AuthedTelemetryRoute
  '/join/$token': typeof JoinTokenRoute
  '/s/$slug': typeof SSlugRoute
  '/': typeof AuthedIndexRoute
  '/ci/$buildId': typeof AuthedCiBuildIdRoute
  '/data/buckets': typeof AuthedDataBucketsRoute
  '/deploy/$template': typeof AuthedDeployTemplateRoute
  '/incidents/$incidentId': typeof AuthedIncidentsIncidentIdRoute
  '/nodes/$nodeId': typeof AuthedNodesNodeIdRoute
  '/nodes/new': typeof AuthedNodesNewRoute
  '/observability/$traceId': typeof AuthedObservabilityTraceIdRoute
  '/services/$serviceId': typeof AuthedServicesServiceIdRoute
  '/services/new': typeof AuthedServicesNewRoute
  '/settings/access': typeof AuthedSettingsAccessRoute
  '/settings/api-keys': typeof AuthedSettingsApiKeysRoute
  '/settings/platform': typeof AuthedSettingsPlatformRoute
  '/stacks/new': typeof AuthedStacksNewRoute
  '/nodes': typeof AuthedNodesIndexRoute
  '/network/domains/$host': typeof AuthedNetworkDomainsHostRoute
  '/network/domains/new': typeof AuthedNetworkDomainsNewRoute
  '/nodes/$nodeId/terminal': typeof AuthedNodesNodeIdTerminalRoute
  '/services/$serviceId/terminal': typeof AuthedServicesServiceIdTerminalRoute
  '/stacks/$name/access': typeof AuthedStacksNameAccessRoute
  '/stacks/$name/analytics': typeof AuthedStacksNameAnalyticsRoute
  '/stacks/$name/backups': typeof AuthedStacksNameBackupsRoute
  '/stacks/$name/data': typeof AuthedStacksNameDataRoute
  '/stacks/$name/messaging': typeof AuthedStacksNameMessagingRoute
  '/stacks/$name/network': typeof AuthedStacksNameNetworkRoute
  '/stacks/$name/observability': typeof AuthedStacksNameObservabilityRoute
  '/stacks/$name/releases': typeof AuthedStacksNameReleasesRoute
  '/stacks/$name/rum-settings': typeof AuthedStacksNameRumSettingsRoute
  '/stacks/$name/settings': typeof AuthedStacksNameSettingsRoute
  '/stacks/$name/source': typeof AuthedStacksNameSourceRoute
  '/stacks/$name/studio': typeof AuthedStacksNameStudioRoute
  '/terminal/sessions/$id': typeof AuthedTerminalSessionsIdRoute
  '/stacks/$name': typeof AuthedStacksNameIndexRoute
  '/stacks/$name/config/jobs': typeof AuthedStacksNameConfigJobsRoute
  '/stacks/$name/config/placement': typeof AuthedStacksNameConfigPlacementRoute
  '/stacks/$name/config/rollout': typeof AuthedStacksNameConfigRolloutRoute
  '/stacks/$name/config/scaling': typeof AuthedStacksNameConfigScalingRoute
  '/stacks/$name/errors/$fingerprint': typeof AuthedStacksNameErrorsFingerprintRoute
  '/stacks/$name/queues/$cluster': typeof AuthedStacksNameQueuesClusterRoute
  '/stacks/$name/replays/$sessionId': typeof AuthedStacksNameReplaysSessionIdRoute
  '/stacks/$name/config': typeof AuthedStacksNameConfigIndexRoute
  '/stacks/$name/errors': typeof AuthedStacksNameErrorsIndexRoute
  '/stacks/$name/queues': typeof AuthedStacksNameQueuesIndexRoute
  '/stacks/$name/replays': typeof AuthedStacksNameReplaysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/app-login': typeof AppLoginRoute
  '/login': typeof LoginRoute
  '/_authed/$': typeof AuthedSplatRoute
  '/_authed/activity': typeof AuthedActivityRoute
  '/_authed/ai': typeof AuthedAiRoute
  '/_authed/alerts': typeof AuthedAlertsRoute
  '/_authed/audit': typeof AuthedAuditRoute
  '/_authed/backups': typeof AuthedBackupsRoute
  '/_authed/blueprints': typeof AuthedBlueprintsRoute
  '/_authed/ci': typeof AuthedCiRoute
  '/_authed/cost': typeof AuthedCostRoute
  '/_authed/data': typeof AuthedDataRoute
  '/_authed/deploy': typeof AuthedDeployRoute
  '/_authed/device': typeof AuthedDeviceRoute
  '/_authed/email': typeof AuthedEmailRoute
  '/_authed/governance': typeof AuthedGovernanceRoute
  '/_authed/incidents': typeof AuthedIncidentsRoute
  '/_authed/ingress': typeof AuthedIngressRoute
  '/_authed/network': typeof AuthedNetworkRoute
  '/_authed/networking': typeof AuthedNetworkingRoute
  '/_authed/overview': typeof AuthedOverviewRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/status-pages': typeof AuthedStatusPagesRoute
  '/_authed/telemetry': typeof AuthedTelemetryRoute
  '/join/$token': typeof JoinTokenRoute
  '/s/$slug': typeof SSlugRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/ci_/$buildId': typeof AuthedCiBuildIdRoute
  '/_authed/data_/buckets': typeof AuthedDataBucketsRoute
  '/_authed/deploy_/$template': typeof AuthedDeployTemplateRoute
  '/_authed/incidents_/$incidentId': typeof AuthedIncidentsIncidentIdRoute
  '/_authed/nodes/$nodeId': typeof AuthedNodesNodeIdRoute
  '/_authed/nodes/new': typeof AuthedNodesNewRoute
  '/_authed/observability/$traceId': typeof AuthedObservabilityTraceIdRoute
  '/_authed/services/$serviceId': typeof AuthedServicesServiceIdRoute
  '/_authed/services/new': typeof AuthedServicesNewRoute
  '/_authed/settings_/access': typeof AuthedSettingsAccessRoute
  '/_authed/settings_/api-keys': typeof AuthedSettingsApiKeysRoute
  '/_authed/settings_/platform': typeof AuthedSettingsPlatformRoute
  '/_authed/stacks/$name': typeof AuthedStacksNameRouteWithChildren
  '/_authed/stacks/new': typeof AuthedStacksNewRoute
  '/_authed/nodes/': typeof AuthedNodesIndexRoute
  '/_authed/network_/domains/$host': typeof AuthedNetworkDomainsHostRoute
  '/_authed/network_/domains/new': typeof AuthedNetworkDomainsNewRoute
  '/_authed/nodes/$nodeId_/terminal': typeof AuthedNodesNodeIdTerminalRoute
  '/_authed/services/$serviceId_/terminal': typeof AuthedServicesServiceIdTerminalRoute
  '/_authed/stacks/$name/access': typeof AuthedStacksNameAccessRoute
  '/_authed/stacks/$name/analytics': typeof AuthedStacksNameAnalyticsRoute
  '/_authed/stacks/$name/backups': typeof AuthedStacksNameBackupsRoute
  '/_authed/stacks/$name/data': typeof AuthedStacksNameDataRoute
  '/_authed/stacks/$name/messaging': typeof AuthedStacksNameMessagingRoute
  '/_authed/stacks/$name/network': typeof AuthedStacksNameNetworkRoute
  '/_authed/stacks/$name/observability': typeof AuthedStacksNameObservabilityRoute
  '/_authed/stacks/$name/releases': typeof AuthedStacksNameReleasesRoute
  '/_authed/stacks/$name/rum-settings': typeof AuthedStacksNameRumSettingsRoute
  '/_authed/stacks/$name/settings': typeof AuthedStacksNameSettingsRoute
  '/_authed/stacks/$name/source': typeof AuthedStacksNameSourceRoute
  '/_authed/stacks/$name/studio': typeof AuthedStacksNameStudioRoute
  '/_authed/terminal/sessions/$id': typeof AuthedTerminalSessionsIdRoute
  '/_authed/stacks/$name/': typeof AuthedStacksNameIndexRoute
  '/_authed/stacks/$name/config/jobs': typeof AuthedStacksNameConfigJobsRoute
  '/_authed/stacks/$name/config/placement': typeof AuthedStacksNameConfigPlacementRoute
  '/_authed/stacks/$name/config/rollout': typeof AuthedStacksNameConfigRolloutRoute
  '/_authed/stacks/$name/config/scaling': typeof AuthedStacksNameConfigScalingRoute
  '/_authed/stacks/$name/errors/$fingerprint': typeof AuthedStacksNameErrorsFingerprintRoute
  '/_authed/stacks/$name/queues/$cluster': typeof AuthedStacksNameQueuesClusterRoute
  '/_authed/stacks/$name/replays/$sessionId': typeof AuthedStacksNameReplaysSessionIdRoute
  '/_authed/stacks/$name/config/': typeof AuthedStacksNameConfigIndexRoute
  '/_authed/stacks/$name/errors/': typeof AuthedStacksNameErrorsIndexRoute
  '/_authed/stacks/$name/queues/': typeof AuthedStacksNameQueuesIndexRoute
  '/_authed/stacks/$name/replays/': typeof AuthedStacksNameReplaysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app-login'
    | '/login'
    | '/$'
    | '/activity'
    | '/ai'
    | '/alerts'
    | '/audit'
    | '/backups'
    | '/blueprints'
    | '/ci'
    | '/cost'
    | '/data'
    | '/deploy'
    | '/device'
    | '/email'
    | '/governance'
    | '/incidents'
    | '/ingress'
    | '/network'
    | '/networking'
    | '/overview'
    | '/settings'
    | '/status-pages'
    | '/telemetry'
    | '/join/$token'
    | '/s/$slug'
    | '/ci/$buildId'
    | '/data/buckets'
    | '/deploy/$template'
    | '/incidents/$incidentId'
    | '/nodes/$nodeId'
    | '/nodes/new'
    | '/observability/$traceId'
    | '/services/$serviceId'
    | '/services/new'
    | '/settings/access'
    | '/settings/api-keys'
    | '/settings/platform'
    | '/stacks/$name'
    | '/stacks/new'
    | '/nodes/'
    | '/network/domains/$host'
    | '/network/domains/new'
    | '/nodes/$nodeId/terminal'
    | '/services/$serviceId/terminal'
    | '/stacks/$name/access'
    | '/stacks/$name/analytics'
    | '/stacks/$name/backups'
    | '/stacks/$name/data'
    | '/stacks/$name/messaging'
    | '/stacks/$name/network'
    | '/stacks/$name/observability'
    | '/stacks/$name/releases'
    | '/stacks/$name/rum-settings'
    | '/stacks/$name/settings'
    | '/stacks/$name/source'
    | '/stacks/$name/studio'
    | '/terminal/sessions/$id'
    | '/stacks/$name/'
    | '/stacks/$name/config/jobs'
    | '/stacks/$name/config/placement'
    | '/stacks/$name/config/rollout'
    | '/stacks/$name/config/scaling'
    | '/stacks/$name/errors/$fingerprint'
    | '/stacks/$name/queues/$cluster'
    | '/stacks/$name/replays/$sessionId'
    | '/stacks/$name/config/'
    | '/stacks/$name/errors/'
    | '/stacks/$name/queues/'
    | '/stacks/$name/replays/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app-login'
    | '/login'
    | '/$'
    | '/activity'
    | '/ai'
    | '/alerts'
    | '/audit'
    | '/backups'
    | '/blueprints'
    | '/ci'
    | '/cost'
    | '/data'
    | '/deploy'
    | '/device'
    | '/email'
    | '/governance'
    | '/incidents'
    | '/ingress'
    | '/network'
    | '/networking'
    | '/overview'
    | '/settings'
    | '/status-pages'
    | '/telemetry'
    | '/join/$token'
    | '/s/$slug'
    | '/'
    | '/ci/$buildId'
    | '/data/buckets'
    | '/deploy/$template'
    | '/incidents/$incidentId'
    | '/nodes/$nodeId'
    | '/nodes/new'
    | '/observability/$traceId'
    | '/services/$serviceId'
    | '/services/new'
    | '/settings/access'
    | '/settings/api-keys'
    | '/settings/platform'
    | '/stacks/new'
    | '/nodes'
    | '/network/domains/$host'
    | '/network/domains/new'
    | '/nodes/$nodeId/terminal'
    | '/services/$serviceId/terminal'
    | '/stacks/$name/access'
    | '/stacks/$name/analytics'
    | '/stacks/$name/backups'
    | '/stacks/$name/data'
    | '/stacks/$name/messaging'
    | '/stacks/$name/network'
    | '/stacks/$name/observability'
    | '/stacks/$name/releases'
    | '/stacks/$name/rum-settings'
    | '/stacks/$name/settings'
    | '/stacks/$name/source'
    | '/stacks/$name/studio'
    | '/terminal/sessions/$id'
    | '/stacks/$name'
    | '/stacks/$name/config/jobs'
    | '/stacks/$name/config/placement'
    | '/stacks/$name/config/rollout'
    | '/stacks/$name/config/scaling'
    | '/stacks/$name/errors/$fingerprint'
    | '/stacks/$name/queues/$cluster'
    | '/stacks/$name/replays/$sessionId'
    | '/stacks/$name/config'
    | '/stacks/$name/errors'
    | '/stacks/$name/queues'
    | '/stacks/$name/replays'
  id:
    | '__root__'
    | '/_authed'
    | '/app-login'
    | '/login'
    | '/_authed/$'
    | '/_authed/activity'
    | '/_authed/ai'
    | '/_authed/alerts'
    | '/_authed/audit'
    | '/_authed/backups'
    | '/_authed/blueprints'
    | '/_authed/ci'
    | '/_authed/cost'
    | '/_authed/data'
    | '/_authed/deploy'
    | '/_authed/device'
    | '/_authed/email'
    | '/_authed/governance'
    | '/_authed/incidents'
    | '/_authed/ingress'
    | '/_authed/network'
    | '/_authed/networking'
    | '/_authed/overview'
    | '/_authed/settings'
    | '/_authed/status-pages'
    | '/_authed/telemetry'
    | '/join/$token'
    | '/s/$slug'
    | '/_authed/'
    | '/_authed/ci_/$buildId'
    | '/_authed/data_/buckets'
    | '/_authed/deploy_/$template'
    | '/_authed/incidents_/$incidentId'
    | '/_authed/nodes/$nodeId'
    | '/_authed/nodes/new'
    | '/_authed/observability/$traceId'
    | '/_authed/services/$serviceId'
    | '/_authed/services/new'
    | '/_authed/settings_/access'
    | '/_authed/settings_/api-keys'
    | '/_authed/settings_/platform'
    | '/_authed/stacks/$name'
    | '/_authed/stacks/new'
    | '/_authed/nodes/'
    | '/_authed/network_/domains/$host'
    | '/_authed/network_/domains/new'
    | '/_authed/nodes/$nodeId_/terminal'
    | '/_authed/services/$serviceId_/terminal'
    | '/_authed/stacks/$name/access'
    | '/_authed/stacks/$name/analytics'
    | '/_authed/stacks/$name/backups'
    | '/_authed/stacks/$name/data'
    | '/_authed/stacks/$name/messaging'
    | '/_authed/stacks/$name/network'
    | '/_authed/stacks/$name/observability'
    | '/_authed/stacks/$name/releases'
    | '/_authed/stacks/$name/rum-settings'
    | '/_authed/stacks/$name/settings'
    | '/_authed/stacks/$name/source'
    | '/_authed/stacks/$name/studio'
    | '/_authed/terminal/sessions/$id'
    | '/_authed/stacks/$name/'
    | '/_authed/stacks/$name/config/jobs'
    | '/_authed/stacks/$name/config/placement'
    | '/_authed/stacks/$name/config/rollout'
    | '/_authed/stacks/$name/config/scaling'
    | '/_authed/stacks/$name/errors/$fingerprint'
    | '/_authed/stacks/$name/queues/$cluster'
    | '/_authed/stacks/$name/replays/$sessionId'
    | '/_authed/stacks/$name/config/'
    | '/_authed/stacks/$name/errors/'
    | '/_authed/stacks/$name/queues/'
    | '/_authed/stacks/$name/replays/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  LoginRoute: typeof LoginRoute
  JoinTokenRoute: typeof JoinTokenRoute
  SSlugRoute: typeof SSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-login': {
      id: '/app-login'
      path: '/app-login'
      fullPath: '/app-login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/telemetry': {
      id: '/_authed/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof AuthedTelemetryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/status-pages': {
      id: '/_authed/status-pages'
      path: '/status-pages'
      fullPath: '/status-pages'
      preLoaderRoute: typeof AuthedStatusPagesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/overview': {
      id: '/_authed/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthedOverviewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/networking': {
      id: '/_authed/networking'
      path: '/networking'
      fullPath: '/networking'
      preLoaderRoute: typeof AuthedNetworkingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/network': {
      id: '/_authed/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AuthedNetworkRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ingress': {
      id: '/_authed/ingress'
      path: '/ingress'
      fullPath: '/ingress'
      preLoaderRoute: typeof AuthedIngressRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/incidents': {
      id: '/_authed/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthedIncidentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/governance': {
      id: '/_authed/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof AuthedGovernanceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/email': {
      id: '/_authed/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AuthedEmailRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/device': {
      id: '/_authed/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof AuthedDeviceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/deploy': {
      id: '/_authed/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof AuthedDeployRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/data': {
      id: '/_authed/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof AuthedDataRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cost': {
      id: '/_authed/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof AuthedCostRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ci': {
      id: '/_authed/ci'
      path: '/ci'
      fullPath: '/ci'
      preLoaderRoute: typeof AuthedCiRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/blueprints': {
      id: '/_authed/blueprints'
      path: '/blueprints'
      fullPath: '/blueprints'
      preLoaderRoute: typeof AuthedBlueprintsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/backups': {
      id: '/_authed/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthedBackupsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit': {
      id: '/_authed/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthedAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/alerts': {
      id: '/_authed/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthedAlertsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ai': {
      id: '/_authed/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthedAiRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/activity': {
      id: '/_authed/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthedActivityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$': {
      id: '/_authed/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthedSplatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/nodes/': {
      id: '/_authed/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof AuthedNodesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stacks/new': {
      id: '/_authed/stacks/new'
      path: '/stacks/new'
      fullPath: '/stacks/new'
      preLoaderRoute: typeof AuthedStacksNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stacks/$name': {
      id: '/_authed/stacks/$name'
      path: '/stacks/$name'
      fullPath: '/stacks/$name'
      preLoaderRoute: typeof AuthedStacksNameRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings_/platform': {
      id: '/_authed/settings_/platform'
      path: '/settings/platform'
      fullPath: '/settings/platform'
      preLoaderRoute: typeof AuthedSettingsPlatformRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings_/api-keys': {
      id: '/_authed/settings_/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthedSettingsApiKeysRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings_/access': {
      id: '/_authed/settings_/access'
      path: '/settings/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof AuthedSettingsAccessRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/services/new': {
      id: '/_authed/services/new'
      path: '/services/new'
      fullPath: '/services/new'
      preLoaderRoute: typeof AuthedServicesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/services/$serviceId': {
      id: '/_authed/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof AuthedServicesServiceIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/observability/$traceId': {
      id: '/_authed/observability/$traceId'
      path: '/observability/$traceId'
      fullPath: '/observability/$traceId'
      preLoaderRoute: typeof AuthedObservabilityTraceIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/nodes/new': {
      id: '/_authed/nodes/new'
      path: '/nodes/new'
      fullPath: '/nodes/new'
      preLoaderRoute: typeof AuthedNodesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/nodes/$nodeId': {
      id: '/_authed/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/nodes/$nodeId'
      preLoaderRoute: typeof AuthedNodesNodeIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/incidents_/$incidentId': {
      id: '/_authed/incidents_/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof AuthedIncidentsIncidentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/deploy_/$template': {
      id: '/_authed/deploy_/$template'
      path: '/deploy/$template'
      fullPath: '/deploy/$template'
      preLoaderRoute: typeof AuthedDeployTemplateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/data_/buckets': {
      id: '/_authed/data_/buckets'
      path: '/data/buckets'
      fullPath: '/data/buckets'
      preLoaderRoute: typeof AuthedDataBucketsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ci_/$buildId': {
      id: '/_authed/ci_/$buildId'
      path: '/ci/$buildId'
      fullPath: '/ci/$buildId'
      preLoaderRoute: typeof AuthedCiBuildIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stacks/$name/': {
      id: '/_authed/stacks/$name/'
      path: '/'
      fullPath: '/stacks/$name/'
      preLoaderRoute: typeof AuthedStacksNameIndexRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/terminal/sessions/$id': {
      id: '/_authed/terminal/sessions/$id'
      path: '/terminal/sessions/$id'
      fullPath: '/terminal/sessions/$id'
      preLoaderRoute: typeof AuthedTerminalSessionsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stacks/$name/studio': {
      id: '/_authed/stacks/$name/studio'
      path: '/studio'
      fullPath: '/stacks/$name/studio'
      preLoaderRoute: typeof AuthedStacksNameStudioRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/source': {
      id: '/_authed/stacks/$name/source'
      path: '/source'
      fullPath: '/stacks/$name/source'
      preLoaderRoute: typeof AuthedStacksNameSourceRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/settings': {
      id: '/_authed/stacks/$name/settings'
      path: '/settings'
      fullPath: '/stacks/$name/settings'
      preLoaderRoute: typeof AuthedStacksNameSettingsRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/rum-settings': {
      id: '/_authed/stacks/$name/rum-settings'
      path: '/rum-settings'
      fullPath: '/stacks/$name/rum-settings'
      preLoaderRoute: typeof AuthedStacksNameRumSettingsRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/releases': {
      id: '/_authed/stacks/$name/releases'
      path: '/releases'
      fullPath: '/stacks/$name/releases'
      preLoaderRoute: typeof AuthedStacksNameReleasesRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/observability': {
      id: '/_authed/stacks/$name/observability'
      path: '/observability'
      fullPath: '/stacks/$name/observability'
      preLoaderRoute: typeof AuthedStacksNameObservabilityRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/network': {
      id: '/_authed/stacks/$name/network'
      path: '/network'
      fullPath: '/stacks/$name/network'
      preLoaderRoute: typeof AuthedStacksNameNetworkRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/messaging': {
      id: '/_authed/stacks/$name/messaging'
      path: '/messaging'
      fullPath: '/stacks/$name/messaging'
      preLoaderRoute: typeof AuthedStacksNameMessagingRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/data': {
      id: '/_authed/stacks/$name/data'
      path: '/data'
      fullPath: '/stacks/$name/data'
      preLoaderRoute: typeof AuthedStacksNameDataRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/backups': {
      id: '/_authed/stacks/$name/backups'
      path: '/backups'
      fullPath: '/stacks/$name/backups'
      preLoaderRoute: typeof AuthedStacksNameBackupsRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/analytics': {
      id: '/_authed/stacks/$name/analytics'
      path: '/analytics'
      fullPath: '/stacks/$name/analytics'
      preLoaderRoute: typeof AuthedStacksNameAnalyticsRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/access': {
      id: '/_authed/stacks/$name/access'
      path: '/access'
      fullPath: '/stacks/$name/access'
      preLoaderRoute: typeof AuthedStacksNameAccessRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/services/$serviceId_/terminal': {
      id: '/_authed/services/$serviceId_/terminal'
      path: '/services/$serviceId/terminal'
      fullPath: '/services/$serviceId/terminal'
      preLoaderRoute: typeof AuthedServicesServiceIdTerminalRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/nodes/$nodeId_/terminal': {
      id: '/_authed/nodes/$nodeId_/terminal'
      path: '/nodes/$nodeId/terminal'
      fullPath: '/nodes/$nodeId/terminal'
      preLoaderRoute: typeof AuthedNodesNodeIdTerminalRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/network_/domains/new': {
      id: '/_authed/network_/domains/new'
      path: '/network/domains/new'
      fullPath: '/network/domains/new'
      preLoaderRoute: typeof AuthedNetworkDomainsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/network_/domains/$host': {
      id: '/_authed/network_/domains/$host'
      path: '/network/domains/$host'
      fullPath: '/network/domains/$host'
      preLoaderRoute: typeof AuthedNetworkDomainsHostRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stacks/$name/replays/': {
      id: '/_authed/stacks/$name/replays/'
      path: '/replays'
      fullPath: '/stacks/$name/replays/'
      preLoaderRoute: typeof AuthedStacksNameReplaysIndexRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/queues/': {
      id: '/_authed/stacks/$name/queues/'
      path: '/queues'
      fullPath: '/stacks/$name/queues/'
      preLoaderRoute: typeof AuthedStacksNameQueuesIndexRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/errors/': {
      id: '/_authed/stacks/$name/errors/'
      path: '/errors'
      fullPath: '/stacks/$name/errors/'
      preLoaderRoute: typeof AuthedStacksNameErrorsIndexRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/config/': {
      id: '/_authed/stacks/$name/config/'
      path: '/config'
      fullPath: '/stacks/$name/config/'
      preLoaderRoute: typeof AuthedStacksNameConfigIndexRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/replays/$sessionId': {
      id: '/_authed/stacks/$name/replays/$sessionId'
      path: '/replays/$sessionId'
      fullPath: '/stacks/$name/replays/$sessionId'
      preLoaderRoute: typeof AuthedStacksNameReplaysSessionIdRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/queues/$cluster': {
      id: '/_authed/stacks/$name/queues/$cluster'
      path: '/queues/$cluster'
      fullPath: '/stacks/$name/queues/$cluster'
      preLoaderRoute: typeof AuthedStacksNameQueuesClusterRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/errors/$fingerprint': {
      id: '/_authed/stacks/$name/errors/$fingerprint'
      path: '/errors/$fingerprint'
      fullPath: '/stacks/$name/errors/$fingerprint'
      preLoaderRoute: typeof AuthedStacksNameErrorsFingerprintRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/config/scaling': {
      id: '/_authed/stacks/$name/config/scaling'
      path: '/config/scaling'
      fullPath: '/stacks/$name/config/scaling'
      preLoaderRoute: typeof AuthedStacksNameConfigScalingRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/config/rollout': {
      id: '/_authed/stacks/$name/config/rollout'
      path: '/config/rollout'
      fullPath: '/stacks/$name/config/rollout'
      preLoaderRoute: typeof AuthedStacksNameConfigRolloutRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/config/placement': {
      id: '/_authed/stacks/$name/config/placement'
      path: '/config/placement'
      fullPath: '/stacks/$name/config/placement'
      preLoaderRoute: typeof AuthedStacksNameConfigPlacementRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/config/jobs': {
      id: '/_authed/stacks/$name/config/jobs'
      path: '/config/jobs'
      fullPath: '/stacks/$name/config/jobs'
      preLoaderRoute: typeof AuthedStacksNameConfigJobsRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
  }
}

interface AuthedStacksNameRouteChildren {
  AuthedStacksNameAccessRoute: typeof AuthedStacksNameAccessRoute
  AuthedStacksNameAnalyticsRoute: typeof AuthedStacksNameAnalyticsRoute
  AuthedStacksNameBackupsRoute: typeof AuthedStacksNameBackupsRoute
  AuthedStacksNameDataRoute: typeof AuthedStacksNameDataRoute
  AuthedStacksNameMessagingRoute: typeof AuthedStacksNameMessagingRoute
  AuthedStacksNameNetworkRoute: typeof AuthedStacksNameNetworkRoute
  AuthedStacksNameObservabilityRoute: typeof AuthedStacksNameObservabilityRoute
  AuthedStacksNameReleasesRoute: typeof AuthedStacksNameReleasesRoute
  AuthedStacksNameRumSettingsRoute: typeof AuthedStacksNameRumSettingsRoute
  AuthedStacksNameSettingsRoute: typeof AuthedStacksNameSettingsRoute
  AuthedStacksNameSourceRoute: typeof AuthedStacksNameSourceRoute
  AuthedStacksNameStudioRoute: typeof AuthedStacksNameStudioRoute
  AuthedStacksNameIndexRoute: typeof AuthedStacksNameIndexRoute
  AuthedStacksNameConfigJobsRoute: typeof AuthedStacksNameConfigJobsRoute
  AuthedStacksNameConfigPlacementRoute: typeof AuthedStacksNameConfigPlacementRoute
  AuthedStacksNameConfigRolloutRoute: typeof AuthedStacksNameConfigRolloutRoute
  AuthedStacksNameConfigScalingRoute: typeof AuthedStacksNameConfigScalingRoute
  AuthedStacksNameErrorsFingerprintRoute: typeof AuthedStacksNameErrorsFingerprintRoute
  AuthedStacksNameQueuesClusterRoute: typeof AuthedStacksNameQueuesClusterRoute
  AuthedStacksNameReplaysSessionIdRoute: typeof AuthedStacksNameReplaysSessionIdRoute
  AuthedStacksNameConfigIndexRoute: typeof AuthedStacksNameConfigIndexRoute
  AuthedStacksNameErrorsIndexRoute: typeof AuthedStacksNameErrorsIndexRoute
  AuthedStacksNameQueuesIndexRoute: typeof AuthedStacksNameQueuesIndexRoute
  AuthedStacksNameReplaysIndexRoute: typeof AuthedStacksNameReplaysIndexRoute
}

const AuthedStacksNameRouteChildren: AuthedStacksNameRouteChildren = {
  AuthedStacksNameAccessRoute: AuthedStacksNameAccessRoute,
  AuthedStacksNameAnalyticsRoute: AuthedStacksNameAnalyticsRoute,
  AuthedStacksNameBackupsRoute: AuthedStacksNameBackupsRoute,
  AuthedStacksNameDataRoute: AuthedStacksNameDataRoute,
  AuthedStacksNameMessagingRoute: AuthedStacksNameMessagingRoute,
  AuthedStacksNameNetworkRoute: AuthedStacksNameNetworkRoute,
  AuthedStacksNameObservabilityRoute: AuthedStacksNameObservabilityRoute,
  AuthedStacksNameReleasesRoute: AuthedStacksNameReleasesRoute,
  AuthedStacksNameRumSettingsRoute: AuthedStacksNameRumSettingsRoute,
  AuthedStacksNameSettingsRoute: AuthedStacksNameSettingsRoute,
  AuthedStacksNameSourceRoute: AuthedStacksNameSourceRoute,
  AuthedStacksNameStudioRoute: AuthedStacksNameStudioRoute,
  AuthedStacksNameIndexRoute: AuthedStacksNameIndexRoute,
  AuthedStacksNameConfigJobsRoute: AuthedStacksNameConfigJobsRoute,
  AuthedStacksNameConfigPlacementRoute: AuthedStacksNameConfigPlacementRoute,
  AuthedStacksNameConfigRolloutRoute: AuthedStacksNameConfigRolloutRoute,
  AuthedStacksNameConfigScalingRoute: AuthedStacksNameConfigScalingRoute,
  AuthedStacksNameErrorsFingerprintRoute:
    AuthedStacksNameErrorsFingerprintRoute,
  AuthedStacksNameQueuesClusterRoute: AuthedStacksNameQueuesClusterRoute,
  AuthedStacksNameReplaysSessionIdRoute: AuthedStacksNameReplaysSessionIdRoute,
  AuthedStacksNameConfigIndexRoute: AuthedStacksNameConfigIndexRoute,
  AuthedStacksNameErrorsIndexRoute: AuthedStacksNameErrorsIndexRoute,
  AuthedStacksNameQueuesIndexRoute: AuthedStacksNameQueuesIndexRoute,
  AuthedStacksNameReplaysIndexRoute: AuthedStacksNameReplaysIndexRoute,
}

const AuthedStacksNameRouteWithChildren =
  AuthedStacksNameRoute._addFileChildren(AuthedStacksNameRouteChildren)

interface AuthedRouteChildren {
  AuthedSplatRoute: typeof AuthedSplatRoute
  AuthedActivityRoute: typeof AuthedActivityRoute
  AuthedAiRoute: typeof AuthedAiRoute
  AuthedAlertsRoute: typeof AuthedAlertsRoute
  AuthedAuditRoute: typeof AuthedAuditRoute
  AuthedBackupsRoute: typeof AuthedBackupsRoute
  AuthedBlueprintsRoute: typeof AuthedBlueprintsRoute
  AuthedCiRoute: typeof AuthedCiRoute
  AuthedCostRoute: typeof AuthedCostRoute
  AuthedDataRoute: typeof AuthedDataRoute
  AuthedDeployRoute: typeof AuthedDeployRoute
  AuthedDeviceRoute: typeof AuthedDeviceRoute
  AuthedEmailRoute: typeof AuthedEmailRoute
  AuthedGovernanceRoute: typeof AuthedGovernanceRoute
  AuthedIncidentsRoute: typeof AuthedIncidentsRoute
  AuthedIngressRoute: typeof AuthedIngressRoute
  AuthedNetworkRoute: typeof AuthedNetworkRoute
  AuthedNetworkingRoute: typeof AuthedNetworkingRoute
  AuthedOverviewRoute: typeof AuthedOverviewRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedStatusPagesRoute: typeof AuthedStatusPagesRoute
  AuthedTelemetryRoute: typeof AuthedTelemetryRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedCiBuildIdRoute: typeof AuthedCiBuildIdRoute
  AuthedDataBucketsRoute: typeof AuthedDataBucketsRoute
  AuthedDeployTemplateRoute: typeof AuthedDeployTemplateRoute
  AuthedIncidentsIncidentIdRoute: typeof AuthedIncidentsIncidentIdRoute
  AuthedNodesNodeIdRoute: typeof AuthedNodesNodeIdRoute
  AuthedNodesNewRoute: typeof AuthedNodesNewRoute
  AuthedObservabilityTraceIdRoute: typeof AuthedObservabilityTraceIdRoute
  AuthedServicesServiceIdRoute: typeof AuthedServicesServiceIdRoute
  AuthedServicesNewRoute: typeof AuthedServicesNewRoute
  AuthedSettingsAccessRoute: typeof AuthedSettingsAccessRoute
  AuthedSettingsApiKeysRoute: typeof AuthedSettingsApiKeysRoute
  AuthedSettingsPlatformRoute: typeof AuthedSettingsPlatformRoute
  AuthedStacksNameRoute: typeof AuthedStacksNameRouteWithChildren
  AuthedStacksNewRoute: typeof AuthedStacksNewRoute
  AuthedNodesIndexRoute: typeof AuthedNodesIndexRoute
  AuthedNetworkDomainsHostRoute: typeof AuthedNetworkDomainsHostRoute
  AuthedNetworkDomainsNewRoute: typeof AuthedNetworkDomainsNewRoute
  AuthedNodesNodeIdTerminalRoute: typeof AuthedNodesNodeIdTerminalRoute
  AuthedServicesServiceIdTerminalRoute: typeof AuthedServicesServiceIdTerminalRoute
  AuthedTerminalSessionsIdRoute: typeof AuthedTerminalSessionsIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSplatRoute: AuthedSplatRoute,
  AuthedActivityRoute: AuthedActivityRoute,
  AuthedAiRoute: AuthedAiRoute,
  AuthedAlertsRoute: AuthedAlertsRoute,
  AuthedAuditRoute: AuthedAuditRoute,
  AuthedBackupsRoute: AuthedBackupsRoute,
  AuthedBlueprintsRoute: AuthedBlueprintsRoute,
  AuthedCiRoute: AuthedCiRoute,
  AuthedCostRoute: AuthedCostRoute,
  AuthedDataRoute: AuthedDataRoute,
  AuthedDeployRoute: AuthedDeployRoute,
  AuthedDeviceRoute: AuthedDeviceRoute,
  AuthedEmailRoute: AuthedEmailRoute,
  AuthedGovernanceRoute: AuthedGovernanceRoute,
  AuthedIncidentsRoute: AuthedIncidentsRoute,
  AuthedIngressRoute: AuthedIngressRoute,
  AuthedNetworkRoute: AuthedNetworkRoute,
  AuthedNetworkingRoute: AuthedNetworkingRoute,
  AuthedOverviewRoute: AuthedOverviewRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedStatusPagesRoute: AuthedStatusPagesRoute,
  AuthedTelemetryRoute: AuthedTelemetryRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedCiBuildIdRoute: AuthedCiBuildIdRoute,
  AuthedDataBucketsRoute: AuthedDataBucketsRoute,
  AuthedDeployTemplateRoute: AuthedDeployTemplateRoute,
  AuthedIncidentsIncidentIdRoute: AuthedIncidentsIncidentIdRoute,
  AuthedNodesNodeIdRoute: AuthedNodesNodeIdRoute,
  AuthedNodesNewRoute: AuthedNodesNewRoute,
  AuthedObservabilityTraceIdRoute: AuthedObservabilityTraceIdRoute,
  AuthedServicesServiceIdRoute: AuthedServicesServiceIdRoute,
  AuthedServicesNewRoute: AuthedServicesNewRoute,
  AuthedSettingsAccessRoute: AuthedSettingsAccessRoute,
  AuthedSettingsApiKeysRoute: AuthedSettingsApiKeysRoute,
  AuthedSettingsPlatformRoute: AuthedSettingsPlatformRoute,
  AuthedStacksNameRoute: AuthedStacksNameRouteWithChildren,
  AuthedStacksNewRoute: AuthedStacksNewRoute,
  AuthedNodesIndexRoute: AuthedNodesIndexRoute,
  AuthedNetworkDomainsHostRoute: AuthedNetworkDomainsHostRoute,
  AuthedNetworkDomainsNewRoute: AuthedNetworkDomainsNewRoute,
  AuthedNodesNodeIdTerminalRoute: AuthedNodesNodeIdTerminalRoute,
  AuthedServicesServiceIdTerminalRoute: AuthedServicesServiceIdTerminalRoute,
  AuthedTerminalSessionsIdRoute: AuthedTerminalSessionsIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  LoginRoute: LoginRoute,
  JoinTokenRoute: JoinTokenRoute,
  SSlugRoute: SSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
