/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedOverviewRouteImport } from './routes/_authed/overview'
import { Route as AuthedNetworkingRouteImport } from './routes/_authed/networking'
import { Route as AuthedIngressRouteImport } from './routes/_authed/ingress'
import { Route as AuthedIncidentsRouteImport } from './routes/_authed/incidents'
import { Route as AuthedGovernanceRouteImport } from './routes/_authed/governance'
import { Route as AuthedExposureRouteImport } from './routes/_authed/exposure'
import { Route as AuthedCostRouteImport } from './routes/_authed/cost'
import { Route as AuthedCiRouteImport } from './routes/_authed/ci'
import { Route as AuthedBlueprintsRouteImport } from './routes/_authed/blueprints'
import { Route as AuthedBackupsRouteImport } from './routes/_authed/backups'
import { Route as AuthedAuditRouteImport } from './routes/_authed/audit'
import { Route as AuthedAlertsRouteImport } from './routes/_authed/alerts'
import { Route as AuthedAiRouteImport } from './routes/_authed/ai'
import { Route as AuthedSplatRouteImport } from './routes/_authed/$'
import { Route as AuthedServicesIndexRouteImport } from './routes/_authed/services/index'
import { Route as AuthedNodesIndexRouteImport } from './routes/_authed/nodes/index'
import { Route as AuthedWorkflowsRunIdRouteImport } from './routes/_authed/workflows.$runId'
import { Route as AuthedStacksNewRouteImport } from './routes/_authed/stacks/new'
import { Route as AuthedStacksNameRouteImport } from './routes/_authed/stacks/$name'
import { Route as AuthedSettingsNotificationsRouteImport } from './routes/_authed/settings_.notifications'
import { Route as AuthedSettingsBackupRouteImport } from './routes/_authed/settings_.backup'
import { Route as AuthedSettingsApiKeysRouteImport } from './routes/_authed/settings_.api-keys'
import { Route as AuthedSettingsAccessRouteImport } from './routes/_authed/settings_.access'
import { Route as AuthedServicesNewRouteImport } from './routes/_authed/services/new'
import { Route as AuthedServicesBuilderRouteImport } from './routes/_authed/services/builder'
import { Route as AuthedServicesServiceIdRouteImport } from './routes/_authed/services/$serviceId'
import { Route as AuthedObservabilityTraceIdRouteImport } from './routes/_authed/observability.$traceId'
import { Route as AuthedNodesNewRouteImport } from './routes/_authed/nodes/new'
import { Route as AuthedNodesNodeIdRouteImport } from './routes/_authed/nodes/$nodeId'
import { Route as AuthedIncidentsIncidentIdRouteImport } from './routes/_authed/incidents_.$incidentId'
import { Route as AuthedDataBucketsRouteImport } from './routes/_authed/data_.buckets'
import { Route as AuthedCiBuildIdRouteImport } from './routes/_authed/ci_.$buildId'
import { Route as AuthedStacksNameIndexRouteImport } from './routes/_authed/stacks/$name.index'
import { Route as AuthedTerminalSessionsIdRouteImport } from './routes/_authed/terminal.sessions.$id'
import { Route as AuthedStacksNameSettingsRouteImport } from './routes/_authed/stacks/$name.settings'
import { Route as AuthedStacksNameReleasesRouteImport } from './routes/_authed/stacks/$name.releases'
import { Route as AuthedStacksNameObservabilityRouteImport } from './routes/_authed/stacks/$name.observability'
import { Route as AuthedStacksNameNetworkRouteImport } from './routes/_authed/stacks/$name.network'
import { Route as AuthedStacksNameMessagingRouteImport } from './routes/_authed/stacks/$name.messaging'
import { Route as AuthedStacksNameDataRouteImport } from './routes/_authed/stacks/$name.data'
import { Route as AuthedStacksNameConfigRouteImport } from './routes/_authed/stacks/$name.config'
import { Route as AuthedStacksNameBackupsRouteImport } from './routes/_authed/stacks/$name.backups'
import { Route as AuthedServicesServiceIdTerminalRouteImport } from './routes/_authed/services/$serviceId_.terminal'
import { Route as AuthedNodesNodeIdTerminalRouteImport } from './routes/_authed/nodes/$nodeId_.terminal'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOverviewRoute = AuthedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNetworkingRoute = AuthedNetworkingRouteImport.update({
  id: '/networking',
  path: '/networking',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIngressRoute = AuthedIngressRouteImport.update({
  id: '/ingress',
  path: '/ingress',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIncidentsRoute = AuthedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGovernanceRoute = AuthedGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExposureRoute = AuthedExposureRouteImport.update({
  id: '/exposure',
  path: '/exposure',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCostRoute = AuthedCostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCiRoute = AuthedCiRouteImport.update({
  id: '/ci',
  path: '/ci',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBlueprintsRoute = AuthedBlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBackupsRoute = AuthedBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditRoute = AuthedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAlertsRoute = AuthedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAiRoute = AuthedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSplatRoute = AuthedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServicesIndexRoute = AuthedServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNodesIndexRoute = AuthedNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkflowsRunIdRoute = AuthedWorkflowsRunIdRouteImport.update({
  id: '/workflows/$runId',
  path: '/workflows/$runId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStacksNewRoute = AuthedStacksNewRouteImport.update({
  id: '/stacks/new',
  path: '/stacks/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStacksNameRoute = AuthedStacksNameRouteImport.update({
  id: '/stacks/$name',
  path: '/stacks/$name',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsNotificationsRoute =
  AuthedSettingsNotificationsRouteImport.update({
    id: '/settings_/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSettingsBackupRoute = AuthedSettingsBackupRouteImport.update({
  id: '/settings_/backup',
  path: '/settings/backup',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsApiKeysRoute = AuthedSettingsApiKeysRouteImport.update({
  id: '/settings_/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsAccessRoute = AuthedSettingsAccessRouteImport.update({
  id: '/settings_/access',
  path: '/settings/access',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServicesNewRoute = AuthedServicesNewRouteImport.update({
  id: '/services/new',
  path: '/services/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServicesBuilderRoute = AuthedServicesBuilderRouteImport.update({
  id: '/services/builder',
  path: '/services/builder',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServicesServiceIdRoute = AuthedServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedObservabilityTraceIdRoute =
  AuthedObservabilityTraceIdRouteImport.update({
    id: '/observability/$traceId',
    path: '/observability/$traceId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedNodesNewRoute = AuthedNodesNewRouteImport.update({
  id: '/nodes/new',
  path: '/nodes/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNodesNodeIdRoute = AuthedNodesNodeIdRouteImport.update({
  id: '/nodes/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIncidentsIncidentIdRoute =
  AuthedIncidentsIncidentIdRouteImport.update({
    id: '/incidents_/$incidentId',
    path: '/incidents/$incidentId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDataBucketsRoute = AuthedDataBucketsRouteImport.update({
  id: '/data_/buckets',
  path: '/data/buckets',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCiBuildIdRoute = AuthedCiBuildIdRouteImport.update({
  id: '/ci_/$buildId',
  path: '/ci/$buildId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStacksNameIndexRoute = AuthedStacksNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedStacksNameRoute,
} as any)
const AuthedTerminalSessionsIdRoute =
  AuthedTerminalSessionsIdRouteImport.update({
    id: '/terminal/sessions/$id',
    path: '/terminal/sessions/$id',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedStacksNameSettingsRoute =
  AuthedStacksNameSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameReleasesRoute =
  AuthedStacksNameReleasesRouteImport.update({
    id: '/releases',
    path: '/releases',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameObservabilityRoute =
  AuthedStacksNameObservabilityRouteImport.update({
    id: '/observability',
    path: '/observability',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameNetworkRoute = AuthedStacksNameNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthedStacksNameRoute,
} as any)
const AuthedStacksNameMessagingRoute =
  AuthedStacksNameMessagingRouteImport.update({
    id: '/messaging',
    path: '/messaging',
    getParentRoute: () => AuthedStacksNameRoute,
  } as any)
const AuthedStacksNameDataRoute = AuthedStacksNameDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AuthedStacksNameRoute,
} as any)
const AuthedStacksNameConfigRoute = AuthedStacksNameConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AuthedStacksNameRoute,
} as any)
const AuthedStacksNameBackupsRoute = AuthedStacksNameBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthedStacksNameRoute,
} as any)
const AuthedServicesServiceIdTerminalRoute =
  AuthedServicesServiceIdTerminalRouteImport.update({
    id: '/services/$serviceId_/terminal',
    path: '/services/$serviceId/terminal',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedNodesNodeIdTerminalRoute =
  AuthedNodesNodeIdTerminalRouteImport.update({
    id: '/nodes/$nodeId_/terminal',
    path: '/nodes/$nodeId/terminal',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AuthedSplatRoute
  '/ai': typeof AuthedAiRoute
  '/alerts': typeof AuthedAlertsRoute
  '/audit': typeof AuthedAuditRoute
  '/backups': typeof AuthedBackupsRoute
  '/blueprints': typeof AuthedBlueprintsRoute
  '/ci': typeof AuthedCiRoute
  '/cost': typeof AuthedCostRoute
  '/exposure': typeof AuthedExposureRoute
  '/governance': typeof AuthedGovernanceRoute
  '/incidents': typeof AuthedIncidentsRoute
  '/ingress': typeof AuthedIngressRoute
  '/networking': typeof AuthedNetworkingRoute
  '/overview': typeof AuthedOverviewRoute
  '/settings': typeof AuthedSettingsRoute
  '/s/$slug': typeof SSlugRoute
  '/ci/$buildId': typeof AuthedCiBuildIdRoute
  '/data/buckets': typeof AuthedDataBucketsRoute
  '/incidents/$incidentId': typeof AuthedIncidentsIncidentIdRoute
  '/nodes/$nodeId': typeof AuthedNodesNodeIdRoute
  '/nodes/new': typeof AuthedNodesNewRoute
  '/observability/$traceId': typeof AuthedObservabilityTraceIdRoute
  '/services/$serviceId': typeof AuthedServicesServiceIdRoute
  '/services/builder': typeof AuthedServicesBuilderRoute
  '/services/new': typeof AuthedServicesNewRoute
  '/settings/access': typeof AuthedSettingsAccessRoute
  '/settings/api-keys': typeof AuthedSettingsApiKeysRoute
  '/settings/backup': typeof AuthedSettingsBackupRoute
  '/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/stacks/$name': typeof AuthedStacksNameRouteWithChildren
  '/stacks/new': typeof AuthedStacksNewRoute
  '/workflows/$runId': typeof AuthedWorkflowsRunIdRoute
  '/nodes/': typeof AuthedNodesIndexRoute
  '/services/': typeof AuthedServicesIndexRoute
  '/nodes/$nodeId/terminal': typeof AuthedNodesNodeIdTerminalRoute
  '/services/$serviceId/terminal': typeof AuthedServicesServiceIdTerminalRoute
  '/stacks/$name/backups': typeof AuthedStacksNameBackupsRoute
  '/stacks/$name/config': typeof AuthedStacksNameConfigRoute
  '/stacks/$name/data': typeof AuthedStacksNameDataRoute
  '/stacks/$name/messaging': typeof AuthedStacksNameMessagingRoute
  '/stacks/$name/network': typeof AuthedStacksNameNetworkRoute
  '/stacks/$name/observability': typeof AuthedStacksNameObservabilityRoute
  '/stacks/$name/releases': typeof AuthedStacksNameReleasesRoute
  '/stacks/$name/settings': typeof AuthedStacksNameSettingsRoute
  '/terminal/sessions/$id': typeof AuthedTerminalSessionsIdRoute
  '/stacks/$name/': typeof AuthedStacksNameIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$': typeof AuthedSplatRoute
  '/ai': typeof AuthedAiRoute
  '/alerts': typeof AuthedAlertsRoute
  '/audit': typeof AuthedAuditRoute
  '/backups': typeof AuthedBackupsRoute
  '/blueprints': typeof AuthedBlueprintsRoute
  '/ci': typeof AuthedCiRoute
  '/cost': typeof AuthedCostRoute
  '/exposure': typeof AuthedExposureRoute
  '/governance': typeof AuthedGovernanceRoute
  '/incidents': typeof AuthedIncidentsRoute
  '/ingress': typeof AuthedIngressRoute
  '/networking': typeof AuthedNetworkingRoute
  '/overview': typeof AuthedOverviewRoute
  '/settings': typeof AuthedSettingsRoute
  '/s/$slug': typeof SSlugRoute
  '/': typeof AuthedIndexRoute
  '/ci/$buildId': typeof AuthedCiBuildIdRoute
  '/data/buckets': typeof AuthedDataBucketsRoute
  '/incidents/$incidentId': typeof AuthedIncidentsIncidentIdRoute
  '/nodes/$nodeId': typeof AuthedNodesNodeIdRoute
  '/nodes/new': typeof AuthedNodesNewRoute
  '/observability/$traceId': typeof AuthedObservabilityTraceIdRoute
  '/services/$serviceId': typeof AuthedServicesServiceIdRoute
  '/services/builder': typeof AuthedServicesBuilderRoute
  '/services/new': typeof AuthedServicesNewRoute
  '/settings/access': typeof AuthedSettingsAccessRoute
  '/settings/api-keys': typeof AuthedSettingsApiKeysRoute
  '/settings/backup': typeof AuthedSettingsBackupRoute
  '/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/stacks/new': typeof AuthedStacksNewRoute
  '/workflows/$runId': typeof AuthedWorkflowsRunIdRoute
  '/nodes': typeof AuthedNodesIndexRoute
  '/services': typeof AuthedServicesIndexRoute
  '/nodes/$nodeId/terminal': typeof AuthedNodesNodeIdTerminalRoute
  '/services/$serviceId/terminal': typeof AuthedServicesServiceIdTerminalRoute
  '/stacks/$name/backups': typeof AuthedStacksNameBackupsRoute
  '/stacks/$name/config': typeof AuthedStacksNameConfigRoute
  '/stacks/$name/data': typeof AuthedStacksNameDataRoute
  '/stacks/$name/messaging': typeof AuthedStacksNameMessagingRoute
  '/stacks/$name/network': typeof AuthedStacksNameNetworkRoute
  '/stacks/$name/observability': typeof AuthedStacksNameObservabilityRoute
  '/stacks/$name/releases': typeof AuthedStacksNameReleasesRoute
  '/stacks/$name/settings': typeof AuthedStacksNameSettingsRoute
  '/terminal/sessions/$id': typeof AuthedTerminalSessionsIdRoute
  '/stacks/$name': typeof AuthedStacksNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/$': typeof AuthedSplatRoute
  '/_authed/ai': typeof AuthedAiRoute
  '/_authed/alerts': typeof AuthedAlertsRoute
  '/_authed/audit': typeof AuthedAuditRoute
  '/_authed/backups': typeof AuthedBackupsRoute
  '/_authed/blueprints': typeof AuthedBlueprintsRoute
  '/_authed/ci': typeof AuthedCiRoute
  '/_authed/cost': typeof AuthedCostRoute
  '/_authed/exposure': typeof AuthedExposureRoute
  '/_authed/governance': typeof AuthedGovernanceRoute
  '/_authed/incidents': typeof AuthedIncidentsRoute
  '/_authed/ingress': typeof AuthedIngressRoute
  '/_authed/networking': typeof AuthedNetworkingRoute
  '/_authed/overview': typeof AuthedOverviewRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/s/$slug': typeof SSlugRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/ci_/$buildId': typeof AuthedCiBuildIdRoute
  '/_authed/data_/buckets': typeof AuthedDataBucketsRoute
  '/_authed/incidents_/$incidentId': typeof AuthedIncidentsIncidentIdRoute
  '/_authed/nodes/$nodeId': typeof AuthedNodesNodeIdRoute
  '/_authed/nodes/new': typeof AuthedNodesNewRoute
  '/_authed/observability/$traceId': typeof AuthedObservabilityTraceIdRoute
  '/_authed/services/$serviceId': typeof AuthedServicesServiceIdRoute
  '/_authed/services/builder': typeof AuthedServicesBuilderRoute
  '/_authed/services/new': typeof AuthedServicesNewRoute
  '/_authed/settings_/access': typeof AuthedSettingsAccessRoute
  '/_authed/settings_/api-keys': typeof AuthedSettingsApiKeysRoute
  '/_authed/settings_/backup': typeof AuthedSettingsBackupRoute
  '/_authed/settings_/notifications': typeof AuthedSettingsNotificationsRoute
  '/_authed/stacks/$name': typeof AuthedStacksNameRouteWithChildren
  '/_authed/stacks/new': typeof AuthedStacksNewRoute
  '/_authed/workflows/$runId': typeof AuthedWorkflowsRunIdRoute
  '/_authed/nodes/': typeof AuthedNodesIndexRoute
  '/_authed/services/': typeof AuthedServicesIndexRoute
  '/_authed/nodes/$nodeId_/terminal': typeof AuthedNodesNodeIdTerminalRoute
  '/_authed/services/$serviceId_/terminal': typeof AuthedServicesServiceIdTerminalRoute
  '/_authed/stacks/$name/backups': typeof AuthedStacksNameBackupsRoute
  '/_authed/stacks/$name/config': typeof AuthedStacksNameConfigRoute
  '/_authed/stacks/$name/data': typeof AuthedStacksNameDataRoute
  '/_authed/stacks/$name/messaging': typeof AuthedStacksNameMessagingRoute
  '/_authed/stacks/$name/network': typeof AuthedStacksNameNetworkRoute
  '/_authed/stacks/$name/observability': typeof AuthedStacksNameObservabilityRoute
  '/_authed/stacks/$name/releases': typeof AuthedStacksNameReleasesRoute
  '/_authed/stacks/$name/settings': typeof AuthedStacksNameSettingsRoute
  '/_authed/terminal/sessions/$id': typeof AuthedTerminalSessionsIdRoute
  '/_authed/stacks/$name/': typeof AuthedStacksNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$'
    | '/ai'
    | '/alerts'
    | '/audit'
    | '/backups'
    | '/blueprints'
    | '/ci'
    | '/cost'
    | '/exposure'
    | '/governance'
    | '/incidents'
    | '/ingress'
    | '/networking'
    | '/overview'
    | '/settings'
    | '/s/$slug'
    | '/ci/$buildId'
    | '/data/buckets'
    | '/incidents/$incidentId'
    | '/nodes/$nodeId'
    | '/nodes/new'
    | '/observability/$traceId'
    | '/services/$serviceId'
    | '/services/builder'
    | '/services/new'
    | '/settings/access'
    | '/settings/api-keys'
    | '/settings/backup'
    | '/settings/notifications'
    | '/stacks/$name'
    | '/stacks/new'
    | '/workflows/$runId'
    | '/nodes/'
    | '/services/'
    | '/nodes/$nodeId/terminal'
    | '/services/$serviceId/terminal'
    | '/stacks/$name/backups'
    | '/stacks/$name/config'
    | '/stacks/$name/data'
    | '/stacks/$name/messaging'
    | '/stacks/$name/network'
    | '/stacks/$name/observability'
    | '/stacks/$name/releases'
    | '/stacks/$name/settings'
    | '/terminal/sessions/$id'
    | '/stacks/$name/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$'
    | '/ai'
    | '/alerts'
    | '/audit'
    | '/backups'
    | '/blueprints'
    | '/ci'
    | '/cost'
    | '/exposure'
    | '/governance'
    | '/incidents'
    | '/ingress'
    | '/networking'
    | '/overview'
    | '/settings'
    | '/s/$slug'
    | '/'
    | '/ci/$buildId'
    | '/data/buckets'
    | '/incidents/$incidentId'
    | '/nodes/$nodeId'
    | '/nodes/new'
    | '/observability/$traceId'
    | '/services/$serviceId'
    | '/services/builder'
    | '/services/new'
    | '/settings/access'
    | '/settings/api-keys'
    | '/settings/backup'
    | '/settings/notifications'
    | '/stacks/new'
    | '/workflows/$runId'
    | '/nodes'
    | '/services'
    | '/nodes/$nodeId/terminal'
    | '/services/$serviceId/terminal'
    | '/stacks/$name/backups'
    | '/stacks/$name/config'
    | '/stacks/$name/data'
    | '/stacks/$name/messaging'
    | '/stacks/$name/network'
    | '/stacks/$name/observability'
    | '/stacks/$name/releases'
    | '/stacks/$name/settings'
    | '/terminal/sessions/$id'
    | '/stacks/$name'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/$'
    | '/_authed/ai'
    | '/_authed/alerts'
    | '/_authed/audit'
    | '/_authed/backups'
    | '/_authed/blueprints'
    | '/_authed/ci'
    | '/_authed/cost'
    | '/_authed/exposure'
    | '/_authed/governance'
    | '/_authed/incidents'
    | '/_authed/ingress'
    | '/_authed/networking'
    | '/_authed/overview'
    | '/_authed/settings'
    | '/s/$slug'
    | '/_authed/'
    | '/_authed/ci_/$buildId'
    | '/_authed/data_/buckets'
    | '/_authed/incidents_/$incidentId'
    | '/_authed/nodes/$nodeId'
    | '/_authed/nodes/new'
    | '/_authed/observability/$traceId'
    | '/_authed/services/$serviceId'
    | '/_authed/services/builder'
    | '/_authed/services/new'
    | '/_authed/settings_/access'
    | '/_authed/settings_/api-keys'
    | '/_authed/settings_/backup'
    | '/_authed/settings_/notifications'
    | '/_authed/stacks/$name'
    | '/_authed/stacks/new'
    | '/_authed/workflows/$runId'
    | '/_authed/nodes/'
    | '/_authed/services/'
    | '/_authed/nodes/$nodeId_/terminal'
    | '/_authed/services/$serviceId_/terminal'
    | '/_authed/stacks/$name/backups'
    | '/_authed/stacks/$name/config'
    | '/_authed/stacks/$name/data'
    | '/_authed/stacks/$name/messaging'
    | '/_authed/stacks/$name/network'
    | '/_authed/stacks/$name/observability'
    | '/_authed/stacks/$name/releases'
    | '/_authed/stacks/$name/settings'
    | '/_authed/terminal/sessions/$id'
    | '/_authed/stacks/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SSlugRoute: typeof SSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/overview': {
      id: '/_authed/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthedOverviewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/networking': {
      id: '/_authed/networking'
      path: '/networking'
      fullPath: '/networking'
      preLoaderRoute: typeof AuthedNetworkingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ingress': {
      id: '/_authed/ingress'
      path: '/ingress'
      fullPath: '/ingress'
      preLoaderRoute: typeof AuthedIngressRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/incidents': {
      id: '/_authed/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthedIncidentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/governance': {
      id: '/_authed/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof AuthedGovernanceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/exposure': {
      id: '/_authed/exposure'
      path: '/exposure'
      fullPath: '/exposure'
      preLoaderRoute: typeof AuthedExposureRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cost': {
      id: '/_authed/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof AuthedCostRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ci': {
      id: '/_authed/ci'
      path: '/ci'
      fullPath: '/ci'
      preLoaderRoute: typeof AuthedCiRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/blueprints': {
      id: '/_authed/blueprints'
      path: '/blueprints'
      fullPath: '/blueprints'
      preLoaderRoute: typeof AuthedBlueprintsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/backups': {
      id: '/_authed/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthedBackupsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit': {
      id: '/_authed/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthedAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/alerts': {
      id: '/_authed/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthedAlertsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ai': {
      id: '/_authed/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthedAiRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$': {
      id: '/_authed/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthedSplatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/services/': {
      id: '/_authed/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AuthedServicesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/nodes/': {
      id: '/_authed/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof AuthedNodesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workflows/$runId': {
      id: '/_authed/workflows/$runId'
      path: '/workflows/$runId'
      fullPath: '/workflows/$runId'
      preLoaderRoute: typeof AuthedWorkflowsRunIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stacks/new': {
      id: '/_authed/stacks/new'
      path: '/stacks/new'
      fullPath: '/stacks/new'
      preLoaderRoute: typeof AuthedStacksNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stacks/$name': {
      id: '/_authed/stacks/$name'
      path: '/stacks/$name'
      fullPath: '/stacks/$name'
      preLoaderRoute: typeof AuthedStacksNameRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings_/notifications': {
      id: '/_authed/settings_/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthedSettingsNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings_/backup': {
      id: '/_authed/settings_/backup'
      path: '/settings/backup'
      fullPath: '/settings/backup'
      preLoaderRoute: typeof AuthedSettingsBackupRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings_/api-keys': {
      id: '/_authed/settings_/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthedSettingsApiKeysRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings_/access': {
      id: '/_authed/settings_/access'
      path: '/settings/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof AuthedSettingsAccessRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/services/new': {
      id: '/_authed/services/new'
      path: '/services/new'
      fullPath: '/services/new'
      preLoaderRoute: typeof AuthedServicesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/services/builder': {
      id: '/_authed/services/builder'
      path: '/services/builder'
      fullPath: '/services/builder'
      preLoaderRoute: typeof AuthedServicesBuilderRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/services/$serviceId': {
      id: '/_authed/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof AuthedServicesServiceIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/observability/$traceId': {
      id: '/_authed/observability/$traceId'
      path: '/observability/$traceId'
      fullPath: '/observability/$traceId'
      preLoaderRoute: typeof AuthedObservabilityTraceIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/nodes/new': {
      id: '/_authed/nodes/new'
      path: '/nodes/new'
      fullPath: '/nodes/new'
      preLoaderRoute: typeof AuthedNodesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/nodes/$nodeId': {
      id: '/_authed/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/nodes/$nodeId'
      preLoaderRoute: typeof AuthedNodesNodeIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/incidents_/$incidentId': {
      id: '/_authed/incidents_/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof AuthedIncidentsIncidentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/data_/buckets': {
      id: '/_authed/data_/buckets'
      path: '/data/buckets'
      fullPath: '/data/buckets'
      preLoaderRoute: typeof AuthedDataBucketsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ci_/$buildId': {
      id: '/_authed/ci_/$buildId'
      path: '/ci/$buildId'
      fullPath: '/ci/$buildId'
      preLoaderRoute: typeof AuthedCiBuildIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stacks/$name/': {
      id: '/_authed/stacks/$name/'
      path: '/'
      fullPath: '/stacks/$name/'
      preLoaderRoute: typeof AuthedStacksNameIndexRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/terminal/sessions/$id': {
      id: '/_authed/terminal/sessions/$id'
      path: '/terminal/sessions/$id'
      fullPath: '/terminal/sessions/$id'
      preLoaderRoute: typeof AuthedTerminalSessionsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stacks/$name/settings': {
      id: '/_authed/stacks/$name/settings'
      path: '/settings'
      fullPath: '/stacks/$name/settings'
      preLoaderRoute: typeof AuthedStacksNameSettingsRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/releases': {
      id: '/_authed/stacks/$name/releases'
      path: '/releases'
      fullPath: '/stacks/$name/releases'
      preLoaderRoute: typeof AuthedStacksNameReleasesRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/observability': {
      id: '/_authed/stacks/$name/observability'
      path: '/observability'
      fullPath: '/stacks/$name/observability'
      preLoaderRoute: typeof AuthedStacksNameObservabilityRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/network': {
      id: '/_authed/stacks/$name/network'
      path: '/network'
      fullPath: '/stacks/$name/network'
      preLoaderRoute: typeof AuthedStacksNameNetworkRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/messaging': {
      id: '/_authed/stacks/$name/messaging'
      path: '/messaging'
      fullPath: '/stacks/$name/messaging'
      preLoaderRoute: typeof AuthedStacksNameMessagingRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/data': {
      id: '/_authed/stacks/$name/data'
      path: '/data'
      fullPath: '/stacks/$name/data'
      preLoaderRoute: typeof AuthedStacksNameDataRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/config': {
      id: '/_authed/stacks/$name/config'
      path: '/config'
      fullPath: '/stacks/$name/config'
      preLoaderRoute: typeof AuthedStacksNameConfigRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/stacks/$name/backups': {
      id: '/_authed/stacks/$name/backups'
      path: '/backups'
      fullPath: '/stacks/$name/backups'
      preLoaderRoute: typeof AuthedStacksNameBackupsRouteImport
      parentRoute: typeof AuthedStacksNameRoute
    }
    '/_authed/services/$serviceId_/terminal': {
      id: '/_authed/services/$serviceId_/terminal'
      path: '/services/$serviceId/terminal'
      fullPath: '/services/$serviceId/terminal'
      preLoaderRoute: typeof AuthedServicesServiceIdTerminalRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/nodes/$nodeId_/terminal': {
      id: '/_authed/nodes/$nodeId_/terminal'
      path: '/nodes/$nodeId/terminal'
      fullPath: '/nodes/$nodeId/terminal'
      preLoaderRoute: typeof AuthedNodesNodeIdTerminalRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedStacksNameRouteChildren {
  AuthedStacksNameBackupsRoute: typeof AuthedStacksNameBackupsRoute
  AuthedStacksNameConfigRoute: typeof AuthedStacksNameConfigRoute
  AuthedStacksNameDataRoute: typeof AuthedStacksNameDataRoute
  AuthedStacksNameMessagingRoute: typeof AuthedStacksNameMessagingRoute
  AuthedStacksNameNetworkRoute: typeof AuthedStacksNameNetworkRoute
  AuthedStacksNameObservabilityRoute: typeof AuthedStacksNameObservabilityRoute
  AuthedStacksNameReleasesRoute: typeof AuthedStacksNameReleasesRoute
  AuthedStacksNameSettingsRoute: typeof AuthedStacksNameSettingsRoute
  AuthedStacksNameIndexRoute: typeof AuthedStacksNameIndexRoute
}

const AuthedStacksNameRouteChildren: AuthedStacksNameRouteChildren = {
  AuthedStacksNameBackupsRoute: AuthedStacksNameBackupsRoute,
  AuthedStacksNameConfigRoute: AuthedStacksNameConfigRoute,
  AuthedStacksNameDataRoute: AuthedStacksNameDataRoute,
  AuthedStacksNameMessagingRoute: AuthedStacksNameMessagingRoute,
  AuthedStacksNameNetworkRoute: AuthedStacksNameNetworkRoute,
  AuthedStacksNameObservabilityRoute: AuthedStacksNameObservabilityRoute,
  AuthedStacksNameReleasesRoute: AuthedStacksNameReleasesRoute,
  AuthedStacksNameSettingsRoute: AuthedStacksNameSettingsRoute,
  AuthedStacksNameIndexRoute: AuthedStacksNameIndexRoute,
}

const AuthedStacksNameRouteWithChildren =
  AuthedStacksNameRoute._addFileChildren(AuthedStacksNameRouteChildren)

interface AuthedRouteChildren {
  AuthedSplatRoute: typeof AuthedSplatRoute
  AuthedAiRoute: typeof AuthedAiRoute
  AuthedAlertsRoute: typeof AuthedAlertsRoute
  AuthedAuditRoute: typeof AuthedAuditRoute
  AuthedBackupsRoute: typeof AuthedBackupsRoute
  AuthedBlueprintsRoute: typeof AuthedBlueprintsRoute
  AuthedCiRoute: typeof AuthedCiRoute
  AuthedCostRoute: typeof AuthedCostRoute
  AuthedExposureRoute: typeof AuthedExposureRoute
  AuthedGovernanceRoute: typeof AuthedGovernanceRoute
  AuthedIncidentsRoute: typeof AuthedIncidentsRoute
  AuthedIngressRoute: typeof AuthedIngressRoute
  AuthedNetworkingRoute: typeof AuthedNetworkingRoute
  AuthedOverviewRoute: typeof AuthedOverviewRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedCiBuildIdRoute: typeof AuthedCiBuildIdRoute
  AuthedDataBucketsRoute: typeof AuthedDataBucketsRoute
  AuthedIncidentsIncidentIdRoute: typeof AuthedIncidentsIncidentIdRoute
  AuthedNodesNodeIdRoute: typeof AuthedNodesNodeIdRoute
  AuthedNodesNewRoute: typeof AuthedNodesNewRoute
  AuthedObservabilityTraceIdRoute: typeof AuthedObservabilityTraceIdRoute
  AuthedServicesServiceIdRoute: typeof AuthedServicesServiceIdRoute
  AuthedServicesBuilderRoute: typeof AuthedServicesBuilderRoute
  AuthedServicesNewRoute: typeof AuthedServicesNewRoute
  AuthedSettingsAccessRoute: typeof AuthedSettingsAccessRoute
  AuthedSettingsApiKeysRoute: typeof AuthedSettingsApiKeysRoute
  AuthedSettingsBackupRoute: typeof AuthedSettingsBackupRoute
  AuthedSettingsNotificationsRoute: typeof AuthedSettingsNotificationsRoute
  AuthedStacksNameRoute: typeof AuthedStacksNameRouteWithChildren
  AuthedStacksNewRoute: typeof AuthedStacksNewRoute
  AuthedWorkflowsRunIdRoute: typeof AuthedWorkflowsRunIdRoute
  AuthedNodesIndexRoute: typeof AuthedNodesIndexRoute
  AuthedServicesIndexRoute: typeof AuthedServicesIndexRoute
  AuthedNodesNodeIdTerminalRoute: typeof AuthedNodesNodeIdTerminalRoute
  AuthedServicesServiceIdTerminalRoute: typeof AuthedServicesServiceIdTerminalRoute
  AuthedTerminalSessionsIdRoute: typeof AuthedTerminalSessionsIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSplatRoute: AuthedSplatRoute,
  AuthedAiRoute: AuthedAiRoute,
  AuthedAlertsRoute: AuthedAlertsRoute,
  AuthedAuditRoute: AuthedAuditRoute,
  AuthedBackupsRoute: AuthedBackupsRoute,
  AuthedBlueprintsRoute: AuthedBlueprintsRoute,
  AuthedCiRoute: AuthedCiRoute,
  AuthedCostRoute: AuthedCostRoute,
  AuthedExposureRoute: AuthedExposureRoute,
  AuthedGovernanceRoute: AuthedGovernanceRoute,
  AuthedIncidentsRoute: AuthedIncidentsRoute,
  AuthedIngressRoute: AuthedIngressRoute,
  AuthedNetworkingRoute: AuthedNetworkingRoute,
  AuthedOverviewRoute: AuthedOverviewRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedCiBuildIdRoute: AuthedCiBuildIdRoute,
  AuthedDataBucketsRoute: AuthedDataBucketsRoute,
  AuthedIncidentsIncidentIdRoute: AuthedIncidentsIncidentIdRoute,
  AuthedNodesNodeIdRoute: AuthedNodesNodeIdRoute,
  AuthedNodesNewRoute: AuthedNodesNewRoute,
  AuthedObservabilityTraceIdRoute: AuthedObservabilityTraceIdRoute,
  AuthedServicesServiceIdRoute: AuthedServicesServiceIdRoute,
  AuthedServicesBuilderRoute: AuthedServicesBuilderRoute,
  AuthedServicesNewRoute: AuthedServicesNewRoute,
  AuthedSettingsAccessRoute: AuthedSettingsAccessRoute,
  AuthedSettingsApiKeysRoute: AuthedSettingsApiKeysRoute,
  AuthedSettingsBackupRoute: AuthedSettingsBackupRoute,
  AuthedSettingsNotificationsRoute: AuthedSettingsNotificationsRoute,
  AuthedStacksNameRoute: AuthedStacksNameRouteWithChildren,
  AuthedStacksNewRoute: AuthedStacksNewRoute,
  AuthedWorkflowsRunIdRoute: AuthedWorkflowsRunIdRoute,
  AuthedNodesIndexRoute: AuthedNodesIndexRoute,
  AuthedServicesIndexRoute: AuthedServicesIndexRoute,
  AuthedNodesNodeIdTerminalRoute: AuthedNodesNodeIdTerminalRoute,
  AuthedServicesServiceIdTerminalRoute: AuthedServicesServiceIdTerminalRoute,
  AuthedTerminalSessionsIdRoute: AuthedTerminalSessionsIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SSlugRoute: SSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
