import {
  SECRET_FAMILY_LABEL,
  SECRET_ORG_LABEL,
  SECRET_OWNER_BLUEPRINT_LABEL,
  SECRET_OWNER_STACK_LABEL,
  type InvService,
} from '@swarmy/core';
import type { SwarmResourceInfo } from '@swarmy/core/protocol';
import type { OrgContext } from '../context';
import { commandRejected, mapDispatchError } from '../errors';
import { writeAudit } from './audit.service';
import { resolveManagerNode } from './dispatch.service';
import {
  consumersOf,
  groupSecrets,
  isValidSecretFamily,
  listRawSecrets,
  liveOrgServices,
  managedLabels,
  nextSecretVersion,
  physicalSecretName,
  type FamilyGroup,
} from './secretsMgr.service';

/**
 * Blueprint-generated secret families and their owner (QA-078). A blueprint
 * stamps `swarmy.secret.owner.{stack,blueprint}` on each secret it creates, so
 *  - deleting the stack removes exactly those families (never by name alone,
 *    never one another service still mounts), audited; and
 *  - redeploying the same stack + blueprint adopts a leftover family instead
 *    of failing on "already exists".
 */

export interface SecretOwner {
  stack: string;
  blueprint: string;
}

const DISPATCH_TIMEOUT_MS = 30_000;

export function ownerLabels(owner: SecretOwner): Record<string, string> {
  return { [SECRET_OWNER_STACK_LABEL]: owner.stack, [SECRET_OWNER_BLUEPRINT_LABEL]: owner.blueprint };
}

/** PURE — who owns a family: every version must carry the same owner, in this org. */
export function familyOwner(raw: readonly SwarmResourceInfo[], orgId: string, family: string): SecretOwner | null {
  const versions = raw.filter((s) => s.labels?.[SECRET_FAMILY_LABEL] === family && (s.labels?.[SECRET_ORG_LABEL] ?? orgId) === orgId);
  if (!versions.length) return null;
  const owners = new Set(
    versions.map((s) => `${s.labels?.[SECRET_OWNER_STACK_LABEL] ?? ''}\u0000${s.labels?.[SECRET_OWNER_BLUEPRINT_LABEL] ?? ''}`),
  );
  if (owners.size !== 1) return null;
  const [stack, blueprint] = [...owners][0]!.split('\u0000') as [string, string];
  return stack && blueprint ? { stack, blueprint } : null;
}

/** PURE — the families a stack's blueprint generated (owner label = this stack). */
export function familiesOwnedByStack(raw: readonly SwarmResourceInfo[], orgId: string, stack: string): FamilyGroup[] {
  return groupSecrets([...raw], orgId).families.filter((g) => familyOwner(raw, orgId, g.family)?.stack === stack);
}

export type EnsuredFamily =
  | { outcome: 'created' | 'rotated'; name: string; value: string }
  | { outcome: 'adopted'; name: string };

/**
 * Create a blueprint's generated family, or reuse a leftover one:
 *  - absent → create v1 with the owner labels;
 *  - present, owned by this SAME stack + blueprint and mounted by nothing →
 *    adopt its current version (the value a surviving data volume was
 *    initialised with), or, when the plan needs the value itself
 *    (`needValue`), rotate to a fresh v(n+1);
 *  - anything else → refused with a plain reason.
 */
export async function ensureBlueprintSecretFamily(
  ctx: OrgContext,
  input: { family: string; owner: SecretOwner; generate: () => string; needValue: boolean },
): Promise<EnsuredFamily> {
  const family = input.family.trim();
  if (!isValidSecretFamily(family)) throw commandRejected(`invalid secret family name "${family}"`);
  const node = await resolveManagerNode(ctx);
  const raw = await listRawSecrets(ctx, node.id);
  const group = groupSecrets(raw, ctx.activeOrgId).families.find((f) => f.family === family);

  const create = async (version: number): Promise<{ name: string; value: string }> => {
    const name = physicalSecretName(family, version);
    if (raw.some((s) => s.name === name)) throw commandRejected(`a Docker secret named "${name}" already exists`);
    const value = input.generate();
    try {
      await ctx.hub.dispatch(
        node.id,
        'secret.create',
        {
          name,
          dataB64: Buffer.from(value, 'utf8').toString('base64'),
          labels: { ...managedLabels(ctx, family, version), ...ownerLabels(input.owner) },
        },
        { timeoutMs: DISPATCH_TIMEOUT_MS },
      );
    } catch (e) {
      throw mapDispatchError(e);
    }
    await writeAudit(ctx, {
      action: version === 1 ? 'secrets.create' : 'secrets.rotate',
      targetType: 'secretFamily',
      targetId: family,
      metadata: { version, bytes: Buffer.byteLength(value, 'utf8'), stack: input.owner.stack, blueprint: input.owner.blueprint },
    });
    return { name, value };
  };

  if (!group) return { outcome: 'created', ...(await create(1)) };

  const owner = familyOwner(raw, ctx.activeOrgId, family);
  if (!owner || owner.stack !== input.owner.stack || owner.blueprint !== input.owner.blueprint) {
    throw commandRejected(
      `secret family "${family}" already exists and was not generated by the ${input.owner.blueprint} blueprint for stack "${input.owner.stack}" — pick another stack name, or delete that secret under Secrets first`,
    );
  }
  const users = consumersOf(liveOrgServices(ctx), group);
  if (users.length) {
    throw commandRejected(
      `secret family "${family}" is still used by ${users.map((u) => u.service.name).join(', ')} — remove the old stack first`,
    );
  }
  if (!input.needValue) {
    const current = group.versions[0]!;
    await writeAudit(ctx, {
      action: 'secrets.adopt',
      targetType: 'secretFamily',
      targetId: family,
      metadata: { version: current.version, stack: input.owner.stack, blueprint: input.owner.blueprint },
    });
    return { outcome: 'adopted', name: current.name };
  }
  const version = nextSecretVersion(group.versions.map((v) => v.version));
  return { outcome: 'rotated', ...(await create(version)) };
}

/**
 * Stack delete: remove the families this stack's blueprint generated. A
 * family any service OUTSIDE the stack still mounts is kept (and reported);
 * the stack's own services are being removed, so they don't count. Audited.
 */
export async function removeStackOwnedSecrets(
  ctx: OrgContext,
  nodeId: string,
  stack: string,
): Promise<{ removed: string[]; kept: string[] }> {
  const raw = await listRawSecrets(ctx, nodeId);
  const owned = familiesOwnedByStack(raw, ctx.activeOrgId, stack);
  const others: InvService[] = liveOrgServices(ctx).filter((s) => s.stack !== stack);
  const removed: string[] = [];
  const kept: string[] = [];
  for (const g of owned) {
    const users = consumersOf(others, g);
    if (users.length) {
      kept.push(g.family);
      continue;
    }
    const removedVersions: number[] = [];
    for (const v of g.versions) {
      // A version the removed tasks still hold is released as they stop — a
      // failed remove leaves that version for the Secrets page, never aborts.
      const ok = await ctx.hub
        .dispatch(nodeId, 'secret.remove', { name: v.name }, { timeoutMs: DISPATCH_TIMEOUT_MS })
        .then(() => true)
        .catch(() => false);
      if (ok) removedVersions.push(v.version);
    }
    if (removedVersions.length) removed.push(g.family);
    await writeAudit(ctx, {
      action: 'secrets.delete',
      targetType: 'secretFamily',
      targetId: g.family,
      metadata: {
        reason: 'stack.remove',
        stack,
        blueprint: familyOwner(raw, ctx.activeOrgId, g.family)?.blueprint ?? null,
        removedVersions: removedVersions.sort((a, b) => a - b),
        ...(removedVersions.length < g.versions.length ? { failedVersions: g.versions.length - removedVersions.length } : {}),
      },
    });
  }
  return { removed, kept };
}
