// Code generated by scripts/gen-sdks.ts. DO NOT EDIT.
//
// Regenerate with: `bun run scripts/gen-sdks.ts` from the repo root.
// Source of truth: packages/api-rest/openapi.json

package swarmy

type ServiceReplicas struct {
	Desired int `json:"desired"`
	Running int `json:"running"`
}

type EnvVar struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type GitRepoWebhook struct {
	URL    string `json:"url"`
	Secret string `json:"secret"`
}

type GitRepoRef struct {
	ID       string `json:"id"`
	FullName string `json:"full_name"`
	CloneURL string `json:"clone_url"`
}

type Node struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	Hostname      string  `json:"hostname"`
	Role          string  `json:"role"`
	Status        string  `json:"status"`
	EngineVersion *string `json:"engine_version"`
	OS            *string `json:"os"`
	Arch          *string `json:"arch"`
	LastSeenAt    *string `json:"last_seen_at"`
}

type NodeList struct {
	Data       []Node  `json:"data"`
	NextCursor *string `json:"next_cursor"`
}

type Problem struct {
	Type       string `json:"type"`
	Title      string `json:"title"`
	Status     int    `json:"status"`
	Detail     string `json:"detail,omitempty"`
	Instance   string `json:"instance,omitempty"`
	SwarmyCode string `json:"swarmy_code,omitempty"`
}

type NodeAvailability struct {
	ID           string `json:"id"`
	Availability string `json:"availability"`
}

type NodeLabels struct {
	ID     string         `json:"id"`
	Labels map[string]any `json:"labels"`
}

type SetNodeLabelsRequest struct {
	Labels map[string]any `json:"labels"`
}

type Removed struct {
	ID      string `json:"id"`
	Removed bool   `json:"removed"`
}

type Service struct {
	ID             string          `json:"id"`
	Name           string          `json:"name"`
	Image          string          `json:"image"`
	Status         string          `json:"status"`
	Replicas       ServiceReplicas `json:"replicas"`
	IngressEnabled bool            `json:"ingress_enabled"`
	NodeID         *string         `json:"node_id"`
	StackID        *string         `json:"stack_id"`
	UpdatedAt      string          `json:"updated_at"`
}

type ServiceList struct {
	Data       []Service `json:"data"`
	NextCursor *string   `json:"next_cursor"`
}

type DeploymentRef struct {
	ID           string `json:"id"`
	DeploymentID string `json:"deployment_id"`
}

type CreateServiceRequest struct {
	Name     string   `json:"name"`
	Image    string   `json:"image"`
	Replicas int      `json:"replicas,omitempty"`
	Command  []string `json:"command,omitempty"`
	Env      []EnvVar `json:"env,omitempty"`
	NodeID   string   `json:"node_id,omitempty"`
}

type ScaleServiceRequest struct {
	Replicas int `json:"replicas"`
}

type Stack struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	ServiceCount int    `json:"service_count"`
	Status       string `json:"status"`
	UpdatedAt    string `json:"updated_at"`
}

type StackList struct {
	Data       []Stack `json:"data"`
	NextCursor *string `json:"next_cursor"`
}

type DeployStackRequest struct {
	Name          string `json:"name"`
	ComposeSource string `json:"compose_source"`
}

type IngressDomainStatus struct {
	Host             string         `json:"host"`
	State            string         `json:"state"`
	Reason           string         `json:"reason"`
	Warnings         []string       `json:"warnings"`
	Gated            bool           `json:"gated"`
	VerifiedAt       *string        `json:"verified_at"`
	VerifiedManually bool           `json:"verified_manually"`
	LastCheckedAt    *string        `json:"last_checked_at"`
	NextCheckAt      *string        `json:"next_check_at"`
	Dns              map[string]any `json:"dns"`
	Certificate      map[string]any `json:"certificate"`
}

type IngressDomain struct {
	ID              string              `json:"id"`
	Host            string              `json:"host"`
	ServiceID       string              `json:"service_id"`
	ServiceName     string              `json:"service_name"`
	TargetPort      int                 `json:"target_port"`
	TLS             string              `json:"tls"`
	PathPrefix      *string             `json:"path_prefix"`
	Www             string              `json:"www,omitempty"`
	CompanionHost   *string             `json:"companion_host"`
	Auto            bool                `json:"auto,omitempty"`
	Status          IngressDomainStatus `json:"status,omitempty"`
	CompanionStatus IngressDomainStatus `json:"companion_status,omitempty"`
}

type IngressDomainList struct {
	Data       []IngressDomain `json:"data"`
	NextCursor *string         `json:"next_cursor"`
}

type AddDomainRequest struct {
	Host       string `json:"host"`
	ServiceID  string `json:"service_id"`
	TargetPort int    `json:"target_port"`
	TLS        string `json:"tls,omitempty"`
	PathPrefix string `json:"path_prefix,omitempty"`
	Www        string `json:"www,omitempty"`
}

type DnsRecordHint struct {
	Type  string `json:"type"`
	Name  string `json:"name"`
	Label string `json:"label"`
	Value string `json:"value"`
	Note  string `json:"note,omitempty"`
}

type UpdateDomainRequest struct {
	Www string `json:"www"`
}

type ApiKey struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Prefix      string   `json:"prefix"`
	Scopes      []string `json:"scopes"`
	LastUsedAt  *string  `json:"last_used_at"`
	CreatedAt   string   `json:"created_at"`
	CreatedByID *string  `json:"created_by_id"`
	RevokedAt   *string  `json:"revoked_at"`
	Status      string   `json:"status"`
}

type ApiKeyList struct {
	Data       []ApiKey `json:"data"`
	NextCursor *string  `json:"next_cursor"`
}

type CreateApiKeyRequest struct {
	Name   string   `json:"name"`
	Scopes []string `json:"scopes,omitempty"`
}

type Revoked struct {
	ID      string `json:"id"`
	Revoked bool   `json:"revoked"`
}

type DnsZone struct {
	ID          string           `json:"id"`
	Zone        string           `json:"zone"`
	Mode        string           `json:"mode"`
	Enabled     bool             `json:"enabled"`
	Ttl         int              `json:"ttl"`
	Serial      int              `json:"serial"`
	ApexToEdge  bool             `json:"apex_to_edge"`
	AutoWww     bool             `json:"auto_www"`
	Nameservers []map[string]any `json:"nameservers"`
}

type DnsZoneList struct {
	Data       []DnsZone `json:"data"`
	NextCursor *string   `json:"next_cursor"`
}

type CreateDnsZoneRequest struct {
	Zone string `json:"zone"`
	Mode string `json:"mode,omitempty"`
}

type DnsDelegationCheck struct {
	Zone        string           `json:"zone"`
	Delegated   bool             `json:"delegated"`
	PublicNs    []string         `json:"public_ns"`
	Nameservers []map[string]any `json:"nameservers"`
}

type DnsRecord struct {
	ID       string `json:"id"`
	ZoneID   string `json:"zone_id"`
	Name     string `json:"name"`
	Type     string `json:"type"`
	Value    string `json:"value"`
	Ttl      *int   `json:"ttl"`
	Priority *int   `json:"priority"`
}

type DnsRecordList struct {
	Data       []DnsRecord `json:"data"`
	NextCursor *string     `json:"next_cursor"`
}

type UpsertDnsRecordRequest struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	Value    string `json:"value"`
	Ttl      int    `json:"ttl,omitempty"`
	Priority int    `json:"priority,omitempty"`
}

type BackupTarget struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	Kind           string  `json:"kind"`
	Endpoint       *string `json:"endpoint"`
	Bucket         string  `json:"bucket"`
	Prefix         *string `json:"prefix"`
	Region         *string `json:"region"`
	HasCredentials bool    `json:"has_credentials"`
	Enabled        bool    `json:"enabled"`
	CreatedAt      string  `json:"created_at"`
}

type BackupTargetList struct {
	Data       []BackupTarget `json:"data"`
	NextCursor *string        `json:"next_cursor"`
}

type AddBackupTargetRequest struct {
	Name            string `json:"name"`
	Kind            string `json:"kind"`
	Endpoint        string `json:"endpoint,omitempty"`
	Bucket          string `json:"bucket"`
	Prefix          string `json:"prefix,omitempty"`
	Region          string `json:"region,omitempty"`
	AccessKeyID     string `json:"access_key_id,omitempty"`
	SecretAccessKey string `json:"secret_access_key,omitempty"`
	ResticPassword  string `json:"restic_password,omitempty"`
}

type Snapshot struct {
	ID         string  `json:"id"`
	Volume     string  `json:"volume"`
	TargetID   string  `json:"target_id"`
	TargetName string  `json:"target_name"`
	Status     string  `json:"status"`
	ResticID   *string `json:"restic_id"`
	SizeBytes  *string `json:"size_bytes"`
	Error      *string `json:"error"`
	StartedAt  string  `json:"started_at"`
	FinishedAt *string `json:"finished_at"`
}

type SnapshotList struct {
	Data       []Snapshot `json:"data"`
	NextCursor *string    `json:"next_cursor"`
}

type BackupRun struct {
	SnapshotID string `json:"snapshot_id"`
	ResticID   string `json:"restic_id"`
	SizeBytes  string `json:"size_bytes"`
}

type BackupVolumeRequest struct {
	TargetID string `json:"target_id"`
	Volume   string `json:"volume"`
	NodeID   string `json:"node_id,omitempty"`
}

type RestoreResult struct {
	TargetVolume  string `json:"target_volume"`
	BytesRestored string `json:"bytes_restored"`
}

type RestoreSnapshotRequest struct {
	SnapshotID   string `json:"snapshot_id"`
	TargetVolume string `json:"target_volume,omitempty"`
	NodeID       string `json:"node_id,omitempty"`
}

type ClusterVolume struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	CsiDriver     string  `json:"csi_driver"`
	AccessMode    string  `json:"access_mode"`
	CapacityBytes *string `json:"capacity_bytes"`
	Status        string  `json:"status"`
	ServiceID     *string `json:"service_id"`
	CreatedAt     string  `json:"created_at"`
}

type ClusterVolumeList struct {
	Data       []ClusterVolume `json:"data"`
	NextCursor *string         `json:"next_cursor"`
}

type RegisterVolumeRequest struct {
	Name          string         `json:"name"`
	CsiDriver     string         `json:"csi_driver"`
	AccessMode    string         `json:"access_mode,omitempty"`
	CapacityBytes int            `json:"capacity_bytes,omitempty"`
	Options       map[string]any `json:"options,omitempty"`
	ServiceID     string         `json:"service_id,omitempty"`
}

type MeshRoute struct {
	ID              string  `json:"id"`
	Kind            string  `json:"kind"`
	TargetServiceID *string `json:"target_service_id"`
	TargetStackID   *string `json:"target_stack_id"`
	Cidr            *string `json:"cidr"`
	Port            *int    `json:"port"`
	PrincipalType   string  `json:"principal_type"`
	PrincipalID     string  `json:"principal_id"`
	ExpiresAt       *string `json:"expires_at"`
	CreatedAt       string  `json:"created_at"`
}

type MeshRouteList struct {
	Data       []MeshRoute `json:"data"`
	NextCursor *string     `json:"next_cursor"`
}

type MeshConnect struct {
	Driver      string `json:"driver"`
	Address     string `json:"address"`
	JoinSnippet string `json:"join_snippet"`
	SetupKey    string `json:"setup_key,omitempty"`
}

type GrantMeshRouteResult struct {
	Route   MeshRoute   `json:"route"`
	Connect MeshConnect `json:"connect"`
}

type GrantMeshRouteRequest struct {
	ServiceID     string `json:"service_id,omitempty"`
	StackID       string `json:"stack_id,omitempty"`
	PrincipalType string `json:"principal_type,omitempty"`
	PrincipalID   string `json:"principal_id"`
	Port          int    `json:"port,omitempty"`
	Proto         string `json:"proto,omitempty"`
	TtlSec        int    `json:"ttl_sec,omitempty"`
}

type NotifyQueued struct {
	Queued bool   `json:"queued"`
	To     string `json:"to"`
}

type NotifyBody struct {
	To       string         `json:"to"`
	Subject  string         `json:"subject"`
	Body     string         `json:"body,omitempty"`
	Html     string         `json:"html,omitempty"`
	Template string         `json:"template,omitempty"`
	Vars     map[string]any `json:"vars,omitempty"`
}

type RegistryCredential struct {
	ID              string  `json:"id"`
	Prefix          string  `json:"prefix"`
	Provider        string  `json:"provider"`
	Label           *string `json:"label"`
	Username        string  `json:"username"`
	HasSecret       bool    `json:"has_secret"`
	LastTestedAt    *string `json:"last_tested_at"`
	LastTestOk      *bool   `json:"last_test_ok"`
	LastTestMessage *string `json:"last_test_message"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
}

type RegistryCredentialList struct {
	Data       []RegistryCredential `json:"data"`
	NextCursor *string              `json:"next_cursor"`
}

type CreateRegistryCredentialBody struct {
	Prefix   string  `json:"prefix"`
	Username string  `json:"username"`
	Secret   string  `json:"secret"`
	Provider string  `json:"provider,omitempty"`
	Label    *string `json:"label"`
}

type UpdateRegistryCredentialBody struct {
	Username string  `json:"username,omitempty"`
	Secret   string  `json:"secret,omitempty"`
	Provider string  `json:"provider,omitempty"`
	Label    *string `json:"label"`
}

type RegistryCredentialDeleted struct {
	Ok bool `json:"ok"`
}

type RegistryTestResult struct {
	Ok              bool   `json:"ok"`
	Status          string `json:"status"`
	Message         string `json:"message"`
	CheckedManifest bool   `json:"checked_manifest"`
}

type TestRegistryCredentialBody struct {
	Image string `json:"image,omitempty"`
}

type GitConnection struct {
	ID          string  `json:"id"`
	Kind        string  `json:"kind"`
	DisplayName string  `json:"display_name"`
	BaseURL     string  `json:"base_url"`
	Account     *string `json:"account"`
	Status      string  `json:"status"`
	RepoCount   int     `json:"repo_count"`
	CreatedAt   string  `json:"created_at"`
}

type GitConnectionList struct {
	Data       []GitConnection `json:"data"`
	NextCursor *string         `json:"next_cursor"`
}

type CreateGitConnectionBody struct {
	Kind        string `json:"kind"`
	Mode        string `json:"mode,omitempty"`
	BaseURL     string `json:"base_url,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	Token       string `json:"token,omitempty"`
	TokenUser   string `json:"token_user,omitempty"`
}

type GitRemoved struct {
	ID      string `json:"id"`
	Removed bool   `json:"removed"`
}

type GitProviderRepo struct {
	ID            string `json:"id"`
	FullName      string `json:"full_name"`
	CloneURL      string `json:"clone_url"`
	HtmlURL       string `json:"html_url"`
	DefaultBranch string `json:"default_branch"`
	Private       bool   `json:"private"`
}

type GitProviderRepoList struct {
	Data       []GitProviderRepo `json:"data"`
	NextCursor *string           `json:"next_cursor"`
}

type GitProviderBranch struct {
	Name string `json:"name"`
	Sha  string `json:"sha"`
}

type GitProviderBranchList struct {
	Data       []GitProviderBranch `json:"data"`
	NextCursor *string             `json:"next_cursor"`
}

type GitRepo struct {
	ID           string  `json:"id"`
	Kind         string  `json:"kind"`
	URL          string  `json:"url"`
	Branch       string  `json:"branch"`
	ConfigPath   string  `json:"config_path"`
	ConnectionID *string `json:"connection_id"`
	FullName     *string `json:"full_name"`
	Autodeploy   bool    `json:"autodeploy"`
	ServiceID    *string `json:"service_id"`
	HasToken     bool    `json:"has_token"`
	CreatedAt    string  `json:"created_at"`
}

type GitRepoList struct {
	Data       []GitRepo `json:"data"`
	NextCursor *string   `json:"next_cursor"`
}

type LinkedGitRepo struct {
	ID              string          `json:"id"`
	URL             string          `json:"url"`
	Branch          string          `json:"branch"`
	ConfigPath      string          `json:"config_path"`
	FullName        *string         `json:"full_name"`
	Webhook         *GitRepoWebhook `json:"webhook"`
	DeployKeyPublic *string         `json:"deploy_key_public"`
}

type LinkGitRepoBody struct {
	ConnectionID string      `json:"connection_id,omitempty"`
	Repo         *GitRepoRef `json:"repo,omitempty"`
	URL          string      `json:"url,omitempty"`
	Branch       string      `json:"branch"`
	ConfigPath   string      `json:"config_path,omitempty"`
	DeployKey    bool        `json:"deploy_key,omitempty"`
}
